---
title: "Table.CombineColumns"
slug: "table-combinecolumns"
category: "Table"
description: "Combines multiple columns into a single column using a combiner function."
syntax: "Table.CombineColumns(table as table, sourceColumns as list, combiner as function, column as text) as table"
returnType: "table"
returnDescription: "A new table where the specified source columns have been merged into one column."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table containing the columns to combine."
  - name: "sourceColumns"
    type: "list"
    required: true
    description: "A list of column names to combine."
  - name: "combiner"
    type: "function"
    required: true
    description: "A combiner function such as Combiner.CombineTextByDelimiter or Combiner.CombineTextByLengths."
  - name: "column"
    type: "text"
    required: true
    description: "The name for the new combined column."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-splitcolumn"
  - "table-addcolumn"
  - "table-transformcolumns"
---

## Remarks

`Table.CombineColumns` merges the values of multiple columns into a single new column using a combiner function, then removes the original source columns. The new column is inserted at the position of the first source column in the column order. Combiner functions from the `Combiner.*` namespace — `Combiner.CombineTextByDelimiter`, `Combiner.CombineTextByLengths`, and `Combiner.CombineTextByRanges` — control how the values are concatenated.

All source columns must be convertible to text for delimiter-based combiners. If numeric or other non-text columns are included, they will be implicitly converted. For more control over formatting, consider using `Table.AddColumn` with an explicit text expression and then removing the originals, which avoids implicit conversions and makes the format transparent.

`Table.CombineColumns` is the inverse of `Table.SplitColumn`: split a column into parts, work with them separately, then recombine. When recombining, ensure the delimiter used here matches what was used to split, or the round-trip will produce unexpected results.

## Examples

### Example 1: Combine first and last name columns from the Employees table

```powerquery
let
    Employees = #table(
        {"EmployeeID", "FirstName", "LastName", "Department"},
        {{"E001","Alice","Smith","Sales"},{"E002","Bob","Jones","Engineering"},{"E003","Charlie","Brown","Marketing"}}
    ),
    Combined = Table.CombineColumns(
        Employees,
        {"FirstName", "LastName"},
        Combiner.CombineTextByDelimiter(" "),
        "FullName"
    )
in
    Combined
```

<!--output
{"columns":[{"name":"EmployeeID","type":"any"},{"name":"FullName","type":"any"},{"name":"Department","type":"any"}],"rows":[{"EmployeeID":"E001","FullName":"Alice Smith","Department":"Sales"},{"EmployeeID":"E002","FullName":"Bob Jones","Department":"Engineering"},{"EmployeeID":"E003","FullName":"Charlie Brown","Department":"Marketing"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Employees",
      "description": "Creates an inline table with EmployeeID, FirstName, LastName, and Department columns for three employees.",
      "output": {"columns":[{"name":"EmployeeID","type":"any"},{"name":"FirstName","type":"any"},{"name":"LastName","type":"any"},{"name":"Department","type":"any"}],"rows":[{"EmployeeID":"E001","FirstName":"Alice","LastName":"Smith","Department":"Sales"},{"EmployeeID":"E002","FirstName":"Bob","LastName":"Jones","Department":"Engineering"},{"EmployeeID":"E003","FirstName":"Charlie","LastName":"Brown","Department":"Marketing"}]}
    },
    {
      "name": "Combined",
      "description": "The final output — merges the FirstName and LastName columns into a single FullName column separated by a space, removing the source columns.",
      "output": {"columns":[{"name":"EmployeeID","type":"any"},{"name":"FullName","type":"any"},{"name":"Department","type":"any"}],"rows":[{"EmployeeID":"E001","FullName":"Alice Smith","Department":"Sales"},{"EmployeeID":"E002","FullName":"Bob Jones","Department":"Engineering"},{"EmployeeID":"E003","FullName":"Charlie Brown","Department":"Marketing"}]}
    }
  ]
}
-->

### Example 2: Build a full address string from city and state

```powerquery
let
    Customers = #table(
        {"CustomerID", "Name", "City", "State"},
        {{1,"Alice","New York","NY"},{2,"Bob","Chicago","IL"},{3,"Charlie","Houston","TX"}}
    ),
    Combined = Table.CombineColumns(
        Customers,
        {"City", "State"},
        Combiner.CombineTextByDelimiter(", "),
        "Location"
    )
in
    Combined
```

<!--output
{"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Location","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","Location":"New York, NY"},{"CustomerID":"2","Name":"Bob","Location":"Chicago, IL"},{"CustomerID":"3","Name":"Charlie","Location":"Houston, TX"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Customers",
      "description": "Creates an inline table with CustomerID, Name, City, and State columns for three customers.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","City":"New York","State":"NY"},{"CustomerID":"2","Name":"Bob","City":"Chicago","State":"IL"},{"CustomerID":"3","Name":"Charlie","City":"Houston","State":"TX"}]}
    },
    {
      "name": "Combined",
      "description": "The final output — merges the City and State columns into a single Location column using \", \" as the delimiter, removing the source columns.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Location","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","Location":"New York, NY"},{"CustomerID":"2","Name":"Bob","Location":"Chicago, IL"},{"CustomerID":"3","Name":"Charlie","Location":"Houston, TX"}]}
    }
  ]
}
-->

### Example 3: Combine fixed-width segments using CombineTextByLengths

```powerquery
Table.CombineColumns(
    #table({"Part1", "Part2", "Part3"}, {{"AB","123","X"}}),
    {"Part1", "Part2", "Part3"},
    Combiner.CombineTextByLengths({2, 3, 1}),
    "Code"
)
```

<!--output
{"columns":[{"name":"Code","type":"any"}],"rows":[{"Code":"AB123X"}]}
-->
