---
title: "Table.ContainsAll"
slug: "table-containsall"
category: "Table"
description: "Returns true if the table contains all of the specified rows."
syntax: "Table.ContainsAll(table as table, rows as list, optional equationCriteria as any) as logical"
returnType: "logical"
returnDescription: "true if every record in the rows list has a matching row in the table; false otherwise."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to search."
  - name: "rows"
    type: "list"
    required: true
    description: "A list of records, each representing a row that must exist in the table."
  - name: "equationCriteria"
    type: "any"
    required: false
    description: "Optional. Column name(s) or comparer to control which fields are compared."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-contains"
  - "table-containsany"
  - "table-isdistinct"
---

## Remarks

`Table.ContainsAll` returns `true` only if every record in the `rows` list has at least one matching row in the table. It is the logical AND of multiple `Table.Contains` checks: all specified rows must be present. If any single row from the list is missing from the table, the function returns `false`.

This is useful for data quality validation — for example, asserting that a dimension table includes all required reference values before proceeding with a transformation, or confirming that a set of mandatory product IDs all appear in a lookup.

The `equationCriteria` parameter restricts which columns participate in the comparison, enabling partial record matching. An empty `rows` list returns `true` by vacuous truth. Like `Table.Contains`, this function does not fold to data sources.

## Examples

### Example 1: Verify all required customers have placed orders

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName"},
        {{1,"Alice"},{2,"Bob"},{3,"Charlie"},{4,"Alice"},{5,"Diana"}}
    ),
    RequiredCustomers = {[CustomerName = "Alice"], [CustomerName = "Diana"]}
in
    Table.ContainsAll(Sales, RequiredCustomers, "CustomerName")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Creates an inline table with OrderID and CustomerName columns for five orders, including Alice and Diana as customers.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice"},{"OrderID":"2","CustomerName":"Bob"},{"OrderID":"3","CustomerName":"Charlie"},{"OrderID":"4","CustomerName":"Alice"},{"OrderID":"5","CustomerName":"Diana"}]}
    },
    {
      "name": "RequiredCustomers",
      "description": "Defines a list of two records representing the customer names that must appear in the Sales table: Alice and Diana.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[CustomerName = \"Alice\"]"},{"Value":"[CustomerName = \"Diana\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns true because both Alice and Diana appear in the CustomerName column of Sales.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
    }
  ]
}
-->

### Example 2: Detect a missing required category

```powerquery
let
    Products = #table(
        {"ProductName", "Category"},
        {{"Widget A","Widgets"},{"Gadget B","Gadgets"},{"Thingamajig E","Misc"}}
    ),
    RequiredCategories = {[Category = "Widgets"], [Category = "Gadgets"], [Category = "Electronics"]}
in
    Table.ContainsAll(Products, RequiredCategories, "Category")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"false"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Creates an inline table with ProductName and Category columns for three products covering Widgets, Gadgets, and Misc categories.",
      "output": {"columns":[{"name":"ProductName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"ProductName":"Widget A","Category":"Widgets"},{"ProductName":"Gadget B","Category":"Gadgets"},{"ProductName":"Thingamajig E","Category":"Misc"}]}
    },
    {
      "name": "RequiredCategories",
      "description": "Defines a list of three records representing the categories that must all appear in Products: Widgets, Gadgets, and Electronics.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[Category = \"Widgets\"]"},{"Value":"[Category = \"Gadgets\"]"},{"Value":"[Category = \"Electronics\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns false because the Electronics category is not present in the Products table.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"false"}]}
    }
  ]
}
-->

### Example 3: Validate all mandatory OrderIDs exist before processing

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product"},
        {{1,"Alice","Widget A"},{2,"Bob","Gadget B"},{3,"Charlie","Widget C"}}
    ),
    MandatoryOrders = {[OrderID = 1], [OrderID = 2], [OrderID = 3]}
in
    Table.ContainsAll(Sales, MandatoryOrders, "OrderID")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Creates an inline table with OrderID, CustomerName, and Product columns for three orders with OrderIDs 1, 2, and 3.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C"}]}
    },
    {
      "name": "MandatoryOrders",
      "description": "Defines a list of three records representing the OrderIDs that must all exist in Sales: 1, 2, and 3.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[OrderID = 1]"},{"Value":"[OrderID = 2]"},{"Value":"[OrderID = 3]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns true because all three required OrderIDs (1, 2, 3) are present in the Sales table.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
    }
  ]
}
-->
