---
title: "Table.Last"
slug: "table-last"
category: "Table"
description: "Returns the last row of the table as a record, or a default value if the table is empty."
syntax: "Table.Last(table as table, optional default as nullable any) as any"
returnType: "any"
returnDescription: "The last row as a record, or the default value if the table is empty."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to retrieve the last row from."
  - name: "default"
    type: "any"
    required: false
    description: "Optional value to return if the table is empty. Defaults to null if omitted."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-first"
  - "table-lastn"
  - "table-singlerow"
---

## Remarks

`Table.Last` returns the last row of a table as a record, enabling field access via `[FieldName]` syntax. If the table is empty and no `default` value is provided, it returns `null`. Providing a default prevents errors in pipelines where the table may occasionally be empty after filtering.

`Table.Last` is the counterpart of `Table.First`. It is most useful when retrieving the most recent record in a time-ordered dataset — for example, the latest transaction after sorting by date, or the final log entry. Combine with `Table.Sort` to ensure deterministic results: `Table.Last(Table.Sort(table, {{"Date", Order.Ascending}}))` reliably returns the row with the maximum date.

For cases where you need to enforce that exactly one row exists, use `Table.SingleRow`. To extract just the bottom-left scalar value without unpacking a record, chain field access: `Table.Last(table)[ColumnName]`. Note that without a prior sort, "last" refers to whatever row physically appears last in the table, which may not be deterministic for database sources.

## Examples

### Example 1: Get the most recent order after sorting by date

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "UnitPrice", "OrderDate"},
        {{1,"Alice","Widget A",25.00,#date(2024,1,15)},
         {2,"Bob","Gadget B",50.00,#date(2024,1,18)},
         {3,"Charlie","Widget C",15.00,#date(2024,2,1)},
         {8,"Diana","Widget C",15.00,#date(2024,4,15)}}
    ),
    Sorted = Table.Sort(Sales, {{"OrderDate", Order.Ascending}})
in
    Table.Last(Sorted)
```

<!--output
{"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 8, CustomerName = \"Diana\", Product = \"Widget C\", UnitPrice = 15, OrderDate = #date(2024,4,15)]"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 4 orders including OrderID, CustomerName, Product, UnitPrice, and OrderDate columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"OrderDate","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A","UnitPrice":"25","OrderDate":"2024-01-15"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B","UnitPrice":"50","OrderDate":"2024-01-18"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C","UnitPrice":"15","OrderDate":"2024-02-01"},{"OrderID":"8","CustomerName":"Diana","Product":"Widget C","UnitPrice":"15","OrderDate":"2024-04-15"}]}
    },
    {
      "name": "Sorted",
      "description": "Sorts the Sales table by OrderDate in ascending order, placing the most recent order last.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"OrderDate","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A","UnitPrice":"25","OrderDate":"2024-01-15"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B","UnitPrice":"50","OrderDate":"2024-01-18"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C","UnitPrice":"15","OrderDate":"2024-02-01"},{"OrderID":"8","CustomerName":"Diana","Product":"Widget C","UnitPrice":"15","OrderDate":"2024-04-15"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns the last row of the sorted table as a record, which is the most recent order (Diana, 2024-04-15).",
      "output": {"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 8, CustomerName = \"Diana\", Product = \"Widget C\", UnitPrice = 15, OrderDate = #date(2024,4,15)]"}]}
    }
  ]
}
-->

### Example 2: Extract the latest order date as a scalar

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "OrderDate"},
        {{1,"Alice",#date(2024,1,15)},{2,"Bob",#date(2024,1,18)},{8,"Diana",#date(2024,4,15)}}
    ),
    Sorted = Table.Sort(Sales, {{"OrderDate", Order.Ascending}})
in
    Table.Last(Sorted)[OrderDate]
```

<!--output
{"columns":[{"name":"Result","type":"date"}],"rows":[{"Result":"2024-04-15"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 3 orders including OrderID, CustomerName, and OrderDate columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"OrderDate","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","OrderDate":"2024-01-15"},{"OrderID":"2","CustomerName":"Bob","OrderDate":"2024-01-18"},{"OrderID":"8","CustomerName":"Diana","OrderDate":"2024-04-15"}]}
    },
    {
      "name": "Sorted",
      "description": "Sorts the Sales table by OrderDate in ascending order, placing the most recent order last.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"OrderDate","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","OrderDate":"2024-01-15"},{"OrderID":"2","CustomerName":"Bob","OrderDate":"2024-01-18"},{"OrderID":"8","CustomerName":"Diana","OrderDate":"2024-04-15"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns the OrderDate field from the last row of the sorted table, yielding the latest order date as a scalar.",
      "output": {"columns":[{"name":"Result","type":"date"}],"rows":[{"Result":"2024-04-15"}]}
    }
  ]
}
-->

### Example 3: Return a safe default for an empty table

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Region"},
        {{1,"Alice","East"},{2,"Bob","West"}}
    ),
    Filtered = Table.SelectRows(Sales, each [Region] = "South")
in
    Table.Last(Filtered, [OrderID = 0, CustomerName = "None", Region = "N/A"])
```

<!--output
{"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 0, CustomerName = \"None\", Region = \"N/A\"]"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 2 orders including OrderID, CustomerName, and Region columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Region","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Region":"East"},{"OrderID":"2","CustomerName":"Bob","Region":"West"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters Sales to keep only rows where Region equals \"South\", producing an empty table since no South orders exist.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Region","type":"any"}],"rows":[]}
    },
    {
      "name": "Result",
      "description": "The final output — since the filtered table is empty, Table.Last returns the provided default record instead of null.",
      "output": {"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 0, CustomerName = \"None\", Region = \"N/A\"]"}]}
    }
  ]
}
-->
