---
title: "Table.ColumnsOfType"
slug: "table-columnsoftype"
category: "Table"
description: "Returns a list of column names whose types match any of the given types."
syntax: "Table.ColumnsOfType(table as table, listOfTypes as list) as list"
returnType: "list"
returnDescription: "A list of column names that match any type in the provided list."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to inspect."
  - name: "listOfTypes"
    type: "list"
    required: true
    description: "A list of types to match against column types (e.g., {type text, type number})."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-columnnames"
  - "table-schema"
  - "table-selectcolumns"
  - "table-transformcolumntypes"
---

## Remarks

`Table.ColumnsOfType` inspects each column's declared type metadata and returns a list of column names whose type matches any type in `listOfTypes`. This enables fully dynamic transformations that adapt to schema changes — for example, trimming all `text` columns, converting all `number` columns to currency format, or selecting only `date` columns for a date-range check.

Type matching compares against the column's declared type, not the inferred type of the values. Columns typed as `type any` (common in untyped `#table` literals) will not match specific types like `type text` or `type number`. To use this function reliably, ensure the table has a typed schema — either via `Table.TransformColumnTypes` or by using a typed `#table` literal with `type table [...]`.

A practical pattern is to combine `Table.ColumnsOfType` with `Table.TransformColumns` to apply a function to all columns of a given type without listing them explicitly. This is more robust than hard-coding column names when working with dynamic or user-provided data.

## Examples

### Example 1: Find all text columns in a typed Employees table

```powerquery
let
    Employees = #table(
        type table [EmployeeID = text, FullName = text, Department = text, Title = text, HireDate = date, Salary = number],
        {{"E001","alice smith","Sales","Sales Rep",#date(2021,3,15),55000}}
    )
in
    Table.ColumnsOfType(Employees, {type text})
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{\"EmployeeID\", \"FullName\", \"Department\", \"Title\"}"}]}
-->

### Example 2: Trim whitespace from all text columns dynamically

Get the list of text columns and pass it to `Table.TransformColumns` to trim each one.

```powerquery
let
    Employees = #table(
        type table [EmployeeID = text, FullName = text, Department = text, Salary = number],
        {{"E001"," alice smith ","Sales",55000},{"E002","BOB JONES ","Engineering",95000}}
    ),
    TextCols   = Table.ColumnsOfType(Employees, {type text}),
    Trimmed    = Table.TransformColumns(Employees, List.Transform(TextCols, each {_, Text.Trim}))
in
    Trimmed
```

<!--output
{"columns":[{"name":"EmployeeID","type":"text"},{"name":"FullName","type":"text"},{"name":"Department","type":"text"},{"name":"Salary","type":"number"}],"rows":[{"EmployeeID":"E001","FullName":"alice smith","Department":"Sales","Salary":"55000"},{"EmployeeID":"E002","FullName":"BOB JONES","Department":"Engineering","Salary":"95000"}]}
-->

### Example 3: Find number and logical columns

```powerquery
let
    Products = #table(
        type table [ProductID = number, ProductName = text, Price = number, InStock = logical],
        {{1,"Widget A",25.00,true},{2,"Gadget B",50.00,true}}
    )
in
    Table.ColumnsOfType(Products, {type number, type logical})
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{\"ProductID\", \"Price\", \"InStock\"}"}]}
-->
