---
title: "Table.ColumnTypes"
slug: "table-columntypes"
category: "Table"
description: "Returns a list of {column name, type} pairs for each column in a table."
syntax: "Table.ColumnTypes(table as table) as list"
returnType: "list"
returnDescription: "A list of two-element lists where the first element is the column name and the second is its type."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to inspect."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-schema"
  - "table-columnnames"
  - "table-transformcolumntypes"
---

## Remarks

`Table.ColumnTypes` returns the declared type for each column. This is useful for dynamically constructing `Table.TransformColumnTypes` calls without hardcoding column names, or for comparing the schema of two tables.

The return value is a list of `{name, type}` pairs suitable for direct use as the second argument to `Table.TransformColumnTypes`.

## Examples

### Example 1: Inspect column types of a table

```powerquery
let
    Source = #table(
        type table [OrderID = number, CustomerID = text, Amount = number],
        {{1, "C001", 250.0}}
    ),
    Types = Table.ColumnTypes(Source)
in
    Types
```

### Example 2: Copy column types from one table to another

Apply the same column types from a reference table to a freshly loaded table.

Input: `Sales`

```powerquery
let
    Reference = Sales,
    NewData   = Table.FromRecords(Table.ToRecords(Sales)),
    Typed     = Table.TransformColumnTypes(NewData, Table.ColumnTypes(Reference))
in
    Typed
```
