---
title: "Table.ContainsAny"
slug: "table-containsany"
category: "Table"
description: "Returns true if the table contains any of the specified rows."
syntax: "Table.ContainsAny(table as table, rows as list, optional equationCriteria as any) as logical"
returnType: "logical"
returnDescription: "true if at least one record in the rows list has a matching row in the table; false otherwise."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to search."
  - name: "rows"
    type: "list"
    required: true
    description: "A list of records, at least one of which must exist in the table."
  - name: "equationCriteria"
    type: "any"
    required: false
    description: "Optional. Column name(s) or comparer to control which fields are compared."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-contains"
  - "table-containsall"
  - "table-isdistinct"
---

## Remarks

`Table.ContainsAny` returns `true` if at least one record from the `rows` list has a matching row in the table. It is the logical OR of multiple `Table.Contains` checks: evaluation stops as soon as a match is found. If no record in the list matches any row in the table, it returns `false`.

This is the complement of `Table.ContainsAll`. Use `Table.ContainsAny` when you want to check whether at least one of several candidate values is present in a dataset — for example, verifying that at least one "high-priority" flag appears before sending an alert, or determining whether any East or North region orders exist in a filtered dataset.

Like `Table.Contains`, the `equationCriteria` parameter can restrict the comparison to specific columns. An empty `rows` list returns `false`. This function does not fold to data sources.

## Examples

### Example 1: Check whether any East or North region orders exist

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Region"},
        {{1,"Alice","East"},{2,"Bob","West"},{3,"Charlie","East"},{4,"Alice","North"}}
    ),
    TargetRegions = {[Region = "North"], [Region = "South"]}
in
    Table.ContainsAny(Sales, TargetRegions, "Region")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->

### Example 2: None of the candidates are present

```powerquery
let
    Products = #table(
        {"Category"},
        {{"Widgets"},{"Gadgets"},{"Misc"}}
    ),
    SearchCategories = {[Category = "Electronics"], [Category = "Furniture"]}
in
    Table.ContainsAny(Products, SearchCategories, "Category")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"false"}]}
-->

### Example 3: Match on a specific customer with full record comparison

```powerquery
let
    Sales = #table(
        {"CustomerName", "Product"},
        {{"Alice","Widget A"},{"Bob","Gadget B"},{"Diana","Widget C"}}
    ),
    Candidates = {[CustomerName = "Diana", Product = "Widget C"], [CustomerName = "Eve", Product = "Gadget D"]}
in
    Table.ContainsAny(Sales, Candidates)
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->
