---
title: "Table.Repeat"
slug: "table-repeat"
category: "Table"
description: "Returns a table that repeats the original table's rows a specified number of times."
syntax: "Table.Repeat(table as table, count as number) as table"
returnType: "table"
returnDescription: "A table containing the original rows repeated count times."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table whose rows are repeated."
  - name: "count"
    type: "number"
    required: true
    description: "The number of times to repeat the table's rows."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-combine"
  - "table-fromrows"
---

## Remarks

`Table.Repeat` returns a new table containing the original rows repeated `count` times in sequence. The result has `Table.RowCount(table) * count` rows. The original row order is preserved within each repetition: if the table has rows A, B, C and `count` is 3, the result is A, B, C, A, B, C, A, B, C.

`Table.Repeat` is useful for generating test datasets with known repeating patterns, creating round-robin schedules, or building cartesian-product-style datasets when combined with `Table.AddIndexColumn`. It is equivalent to `Table.Combine(List.Repeat({table}, count))`.

Note that `Table.Repeat` is not the same as repeating each individual row N times — that would require `Table.AddColumn` with a list expansion. `Table.Repeat` repeats the entire table as a block.

## Examples

### Example 1: Repeat the Products table to generate a multi-cycle test dataset

```powerquery
let
    Products = #table(
        {"ProductID","ProductName","Category"},
        {{1,"Widget A","Widgets"},{2,"Gadget B","Gadgets"},{3,"Widget C","Widgets"}}
    )
in
    Table.Repeat(Products, 3)
```

<!--output
{"columns":[{"name":"ProductID","type":"any"},{"name":"ProductName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"},{"ProductID":"3","ProductName":"Widget C","Category":"Widgets"},{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"},{"ProductID":"3","ProductName":"Widget C","Category":"Widgets"},{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"},{"ProductID":"3","ProductName":"Widget C","Category":"Widgets"}]}
-->

### Example 2: Build a repeating status cycle and add a sequence index

Combine `Table.Repeat` with `Table.AddIndexColumn` to create an indexed round-robin assignment.

```powerquery
let
    Regions    = #table({"Region"},{{"East"},{"West"},{"North"}}),
    Repeated   = Table.Repeat(Regions, 3),
    WithIndex  = Table.AddIndexColumn(Repeated, "Cycle", 0, 1, type number)
in
    WithIndex
```

<!--output
{"columns":[{"name":"Region","type":"any"},{"name":"Cycle","type":"number"}],"rows":[{"Region":"East","Cycle":"0"},{"Region":"West","Cycle":"1"},{"Region":"North","Cycle":"2"},{"Region":"East","Cycle":"3"},{"Region":"West","Cycle":"4"},{"Region":"North","Cycle":"5"},{"Region":"East","Cycle":"6"},{"Region":"West","Cycle":"7"},{"Region":"North","Cycle":"8"}]}
-->

### Example 3: Confirm row count after repetition

```powerquery
let
    Customers = #table(
        {"CustomerID","Name"},
        {{1,"Alice"},{2,"Bob"},{3,"Charlie"},{4,"Diana"}}
    ),
    Repeated = Table.Repeat(Customers, 5)
in
    Table.RowCount(Repeated)
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"20"}]}
-->
