---
title: "Table.Column"
slug: "table-column"
category: "Table"
description: "Returns a list of all values from the named column."
syntax: "Table.Column(table as table, column as text) as list"
returnType: "list"
returnDescription: "A list containing all values from the specified column."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to extract the column from."
  - name: "column"
    type: "text"
    required: true
    description: "The name of the column to extract."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-columnnames"
  - "table-selectcolumns"
  - "table-tolist"
---

## Remarks

`Table.Column` extracts all values from a named column as a list. This is a concise alternative to `Table.ToList` when you only need one column's values. The result is commonly passed to list aggregation functions such as `List.Sum`, `List.Max`, or `List.Distinct`.

If the column name does not exist in the table, an error is raised.

## Examples

### Example 1: Extract a column as a list

```powerquery
Table.Column(
    #table({"Product", "Amount"}, {{"A", 250}, {"B", 180}, {"C", 420}}),
    "Amount"
)
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{250, 180, 420}"}]}
-->

### Example 2: Sum values from a column

```powerquery
let
    Source = #table({"Item", "Sales"}, {{"X", 100}, {"Y", 200}, {"Z", 300}}),
    Values = Table.Column(Source, "Sales"),
    Total  = List.Sum(Values)
in
    Total
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"600"}]}
-->
