---
title: "Table.Column"
slug: "table-column"
category: "Table"
description: "Returns a list of all values from the named column."
syntax: "Table.Column(table as table, column as text) as list"
returnType: "list"
returnDescription: "A list containing all values from the specified column."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to extract the column from."
  - name: "column"
    type: "text"
    required: true
    description: "The name of the column to extract."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-columnnames"
  - "table-selectcolumns"
  - "table-tolist"
---

## Remarks

`Table.Column` extracts all values from a named column and returns them as a list. It is a concise shorthand for `Table.ToColumns(Table.SelectColumns(table, {column}))`{0}` and the result is identical to accessing a column via `table[ColumnName]` syntax. The `table[ColumnName]` shorthand is often preferred for brevity in expressions, while `Table.Column` is clearer in procedural step-by-step queries.

The returned list is commonly passed to aggregation functions such as `List.Sum`, `List.Max`, `List.Distinct`, or `List.Average`. If the column name does not exist, an error is raised at runtime. To avoid this in dynamic scenarios, guard with `Table.HasColumns` first.

`Table.Column` does not fold to data sources. If you need aggregate values from a large database table, prefer native aggregation via `Table.Group` or source-side functions to preserve query folding.

## Examples

### Example 1: Extract all unit prices from the Products table

```powerquery
let
    Products = #table(
        type table [ProductID = number, ProductName = text, Category = text, Price = number, InStock = logical],
        {{1, "Widget A", "Widgets", 25.00, true}, {2, "Gadget B", "Gadgets", 50.00, true},
         {3, "Widget C", "Widgets", 15.00, false}, {4, "Gadget D", "Gadgets", 75.00, true},
         {5, "Thingamajig E", "Misc", 120.00, false}}
    )
in
    Table.Column(Products, "Price")
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{25, 50, 15, 75, 120}"}]}
-->

### Example 2: Sum all order quantities

Use the extracted list directly in an aggregation function.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "Category", "UnitPrice", "Quantity", "OrderDate", "Region"},
        {{1,"Alice","Widget A","Widgets",25.00,4,#date(2024,1,15),"East"},
         {2,"Bob","Gadget B","Gadgets",50.00,2,#date(2024,1,18),"West"},
         {3,"Charlie","Widget C","Widgets",15.00,10,#date(2024,2,1),"East"}}
    ),
    Quantities = Table.Column(Sales, "Quantity")
in
    List.Sum(Quantities)
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"16"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines an inline table with OrderID, CustomerName, Product, Category, UnitPrice, Quantity, OrderDate, and Region columns for three orders.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"Category","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"Quantity","type":"any"},{"name":"OrderDate","type":"any"},{"name":"Region","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A","Category":"Widgets","UnitPrice":"25","Quantity":"4","OrderDate":"2024-01-15","Region":"East"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B","Category":"Gadgets","UnitPrice":"50","Quantity":"2","OrderDate":"2024-01-18","Region":"West"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C","Category":"Widgets","UnitPrice":"15","Quantity":"10","OrderDate":"2024-02-01","Region":"East"}]}
    },
    {
      "name": "Quantities",
      "description": "Extracts all values from the Quantity column of Sales as a list: {4, 2, 10}.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"4"},{"Value":"2"},{"Value":"10"}]}
    },
    {
      "name": "Result",
      "description": "The final output — sums the Quantities list to produce the total number of units ordered.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"16"}]}
    }
  ]
}
-->

### Example 3: Get distinct customer names

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product"},
        {{1,"Alice","Widget A"},{2,"Bob","Gadget B"},{3,"Alice","Widget C"},{4,"Bob","Gadget D"}}
    ),
    Names = Table.Column(Sales, "CustomerName")
in
    List.Distinct(Names)
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{\"Alice\", \"Bob\"}"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines an inline table with OrderID, CustomerName, and Product columns for four orders, where Alice and Bob each appear twice.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B"},{"OrderID":"3","CustomerName":"Alice","Product":"Widget C"},{"OrderID":"4","CustomerName":"Bob","Product":"Gadget D"}]}
    },
    {
      "name": "Names",
      "description": "Extracts all values from the CustomerName column as a list, including duplicates: {\"Alice\", \"Bob\", \"Alice\", \"Bob\"}.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"Alice"},{"Value":"Bob"},{"Value":"Alice"},{"Value":"Bob"}]}
    },
    {
      "name": "Result",
      "description": "The final output — removes duplicates from the Names list, returning only the unique customer names.",
      "output": {"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{\"Alice\", \"Bob\"}"}]}
    }
  ]
}
-->
