---
title: "Table.ContainsAny"
slug: "table-containsany"
category: "Table"
description: "Returns true if the table contains any of the specified rows."
syntax: "Table.ContainsAny(table as table, rows as list, optional equationCriteria as any) as logical"
returnType: "logical"
returnDescription: "true if at least one record in the rows list has a matching row in the table; false otherwise."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to search."
  - name: "rows"
    type: "list"
    required: true
    description: "A list of records, at least one of which must exist in the table."
  - name: "equationCriteria"
    type: "any"
    required: false
    description: "Optional. Column name(s) or comparer to control which fields are compared."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-contains"
  - "table-containsall"
  - "table-isdistinct"
---

## Remarks

`Table.ContainsAny` returns `true` if at least one record from the `rows` list has a matching row in the table. It is the logical OR of multiple `Table.Contains` checks: evaluation stops as soon as a match is found. If no record in the list matches any row in the table, it returns `false`.

This is the complement of `Table.ContainsAll`. Use `Table.ContainsAny` when you want to check whether at least one of several candidate values is present in a dataset — for example, verifying that at least one "high-priority" flag appears before sending an alert, or determining whether any East or North region orders exist in a filtered dataset.

Like `Table.Contains`, the `equationCriteria` parameter can restrict the comparison to specific columns. An empty `rows` list returns `false`. This function does not fold to data sources.

## Examples

### Example 1: Check whether any East or North region orders exist

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Region"},
        {{1,"Alice","East"},{2,"Bob","West"},{3,"Charlie","East"},{4,"Alice","North"}}
    ),
    TargetRegions = {[Region = "North"], [Region = "South"]}
in
    Table.ContainsAny(Sales, TargetRegions, "Region")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Creates an inline table with OrderID, CustomerName, and Region columns for four orders spanning East, West, East, and North regions.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Region","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Region":"East"},{"OrderID":"2","CustomerName":"Bob","Region":"West"},{"OrderID":"3","CustomerName":"Charlie","Region":"East"},{"OrderID":"4","CustomerName":"Alice","Region":"North"}]}
    },
    {
      "name": "TargetRegions",
      "description": "Defines a list of two records representing the regions to search for: North and South.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[Region = \"North\"]"},{"Value":"[Region = \"South\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns true because at least one of the target regions (North) appears in the Sales table.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
    }
  ]
}
-->

### Example 2: None of the candidates are present

```powerquery
let
    Products = #table(
        {"Category"},
        {{"Widgets"},{"Gadgets"},{"Misc"}}
    ),
    SearchCategories = {[Category = "Electronics"], [Category = "Furniture"]}
in
    Table.ContainsAny(Products, SearchCategories, "Category")
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"false"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Creates an inline table with a single Category column containing three values: Widgets, Gadgets, and Misc.",
      "output": {"columns":[{"name":"Category","type":"any"}],"rows":[{"Category":"Widgets"},{"Category":"Gadgets"},{"Category":"Misc"}]}
    },
    {
      "name": "SearchCategories",
      "description": "Defines a list of two records representing the categories to search for: Electronics and Furniture.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[Category = \"Electronics\"]"},{"Value":"[Category = \"Furniture\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns false because neither Electronics nor Furniture appears in the Products table.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"false"}]}
    }
  ]
}
-->

### Example 3: Match on a specific customer with full record comparison

```powerquery
let
    Sales = #table(
        {"CustomerName", "Product"},
        {{"Alice","Widget A"},{"Bob","Gadget B"},{"Diana","Widget C"}}
    ),
    Candidates = {[CustomerName = "Diana", Product = "Widget C"], [CustomerName = "Eve", Product = "Gadget D"]}
in
    Table.ContainsAny(Sales, Candidates)
```

<!--output
{"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Creates an inline table with CustomerName and Product columns for three orders.",
      "output": {"columns":[{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"}],"rows":[{"CustomerName":"Alice","Product":"Widget A"},{"CustomerName":"Bob","Product":"Gadget B"},{"CustomerName":"Diana","Product":"Widget C"}]}
    },
    {
      "name": "Candidates",
      "description": "Defines a list of two records to search for: Diana with Widget C, and Eve with Gadget D.",
      "output": {"columns":[{"name":"Value","type":"any"}],"rows":[{"Value":"[CustomerName = \"Diana\", Product = \"Widget C\"]"},{"Value":"[CustomerName = \"Eve\", Product = \"Gadget D\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns true because the first candidate (Diana / Widget C) matches an exact row in the Sales table.",
      "output": {"columns":[{"name":"Result","type":"logical"}],"rows":[{"Result":"true"}]}
    }
  ]
}
-->
