---
title: "Table.Keys"
slug: "table-keys"
category: "Table"
description: "Returns a list of key records defined on the table type."
syntax: "Table.Keys(table as table) as list"
returnType: "list"
returnDescription: "A list of records, each describing a key defined on the table."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table whose key metadata is returned."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-addkey"
  - "table-schema"
  - "table-columnnames"
---

## Remarks

`Table.Keys` returns a list of records describing the key declarations on a table's type metadata. Each element has two fields:
- `Columns`: a list of column names forming the key.
- `Primary`: `true` if the key is a primary key, `false` for candidate (non-primary) keys.

Keys are typically declared using `Table.AddKey` or inherited from a data source that exposes primary key metadata (such as SQL Server or certain OData sources). If no keys are declared, `Table.Keys` returns an empty list `{}`.

This function is useful for introspection — for example, confirming that `Table.AddKey` registered correctly, or inspecting which columns a connector has identified as primary keys. The returned list can be traversed programmatically to extract column names or filter for primary keys only.

## Examples

### Example 1: Inspect keys on a table with no keys declared

A plain `#table` literal carries no key metadata.

```powerquery
Table.Keys(
    #table({"CustomerID", "Name", "City"},
           {{1,"Alice","New York"},{2,"Bob","Chicago"}})
)
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{}"}]}
-->

### Example 2: Inspect keys after declaring a primary key

```powerquery
let
    Customers = #table(
        {"CustomerID", "Name", "Email"},
        {{1,"Alice","alice@example.com"},{2,"Bob","bob@example.com"}}
    ),
    WithKey = Table.AddKey(Customers, {"CustomerID"}, true)
in
    Table.Keys(WithKey)
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{[Columns = {\"CustomerID\"}, Primary = true]}"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Customers",
      "description": "Defines an inline Customers table with CustomerID, Name, and Email columns containing two rows — the table has no key metadata at this point.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Email","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","Email":"alice@example.com"},{"CustomerID":"2","Name":"Bob","Email":"bob@example.com"}]}
    },
    {
      "name": "WithKey",
      "description": "Calls Table.AddKey to declare CustomerID as a primary key on the Customers table, adding key metadata to the table's type without changing its rows.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Email","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","Email":"alice@example.com"},{"CustomerID":"2","Name":"Bob","Email":"bob@example.com"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.Keys returns a list with one record describing the declared primary key on the CustomerID column.",
      "output": {"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{[Columns = {\"CustomerID\"}, Primary = true]}"}]}
    }
  ]
}
-->

### Example 3: Declare both a primary and a non-primary key, then inspect

```powerquery
let
    Products = #table(
        {"ProductID","ProductName","Category"},
        {{1,"Widget A","Widgets"},{2,"Gadget B","Gadgets"}}
    ),
    Step1 = Table.AddKey(Products, {"ProductID"}, true),
    Step2 = Table.AddKey(Step1, {"ProductName"}, false)
in
    Table.Keys(Step2)
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{[Columns = {\"ProductID\"}, Primary = true], [Columns = {\"ProductName\"}, Primary = false]}"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Defines an inline Products table with ProductID, ProductName, and Category columns containing two rows — no key metadata is set yet.",
      "output": {"columns":[{"name":"ProductID","type":"any"},{"name":"ProductName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"}]}
    },
    {
      "name": "Step1",
      "description": "Adds a primary key declaration on the ProductID column, registering it as the table's primary key in type metadata.",
      "output": {"columns":[{"name":"ProductID","type":"any"},{"name":"ProductName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"}]}
    },
    {
      "name": "Step2",
      "description": "Adds a second (non-primary) key declaration on the ProductName column, so the table now has two key definitions in its metadata.",
      "output": {"columns":[{"name":"ProductID","type":"any"},{"name":"ProductName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.Keys returns a list of two records: one describing the primary key on ProductID and one describing the non-primary key on ProductName.",
      "output": {"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{[Columns = {\"ProductID\"}, Primary = true], [Columns = {\"ProductName\"}, Primary = false]}"}]}
    }
  ]
}
-->
