---
title: "Table.FuzzyNestedJoin"
slug: "table-fuzzynestedjoin"
category: "Table"
description: "Joins two tables using fuzzy string matching and produces a nested table column of matches."
syntax: "Table.FuzzyNestedJoin(table1 as table, key1 as any, table2 as table, key2 as any, newColumnName as text, optional joinKind as nullable number, optional joinOptions as nullable record) as table"
returnType: "table"
returnDescription: "The left table with a new column containing nested tables of fuzzy-matched rows from the right table."
parameters:
  - name: "table1"
    type: "table"
    required: true
    description: "The left table."
  - name: "key1"
    type: "any"
    required: true
    description: "The key column name or list of column names from table1."
  - name: "table2"
    type: "table"
    required: true
    description: "The right table."
  - name: "key2"
    type: "any"
    required: true
    description: "The key column name or list of column names from table2."
  - name: "newColumnName"
    type: "text"
    required: true
    description: "The name for the new nested table column added to table1."
  - name: "joinKind"
    type: "number"
    required: false
    description: "Optional. The join type (JoinKind.Inner, JoinKind.LeftOuter, etc.). Defaults to JoinKind.LeftOuter."
  - name: "joinOptions"
    type: "record"
    required: false
    description: "Optional record with fuzzy matching options: Threshold, IgnoreCase, IgnoreSpace, NumberOfMatches, TransformationTable."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: false
  excelOnline: false
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-nestedjoin"
  - "table-fuzzyjoin"
  - "table-fuzzygroup"
  - "table-expandtablecolumn"
---

## Remarks

`Table.FuzzyNestedJoin` is the fuzzy-matching counterpart of `Table.NestedJoin`. Instead of requiring exact key equality, it matches keys using approximate string similarity and stores all matching right-table rows in a nested table column. This is useful when you need to inspect all fuzzy matches per left-table row before deciding which to keep, or when you want to count matches rather than flatten them immediately.

The `joinOptions` record accepts the same fields as `Table.FuzzyJoin`: `Threshold`, `IgnoreCase`, `IgnoreSpace`, `NumberOfMatches`, and `TransformationTable`. The default `joinKind` is `JoinKind.LeftOuter`. Use `Table.ExpandTableColumn` to flatten the nested matches into additional columns.

Prefer `Table.FuzzyNestedJoin` over `Table.FuzzyJoin` when you want to handle one-to-many matches explicitly — for example, counting the number of fuzzy matches per row or selecting the best match based on a custom criterion. For a direct flat join without the nested intermediate step, use `Table.FuzzyJoin`.

## Examples

### Example 1: Fuzzy nested join — Sales with misspelled names against Customers

```powerquery
let
    Orders = #table(
        {"OrderID", "CustomerName", "Amount"},
        {{1,"Alise",250},{2,"Bobb",180},{3,"Charlei",300},{4,"Diana",150}}
    ),
    Customers = #table(
        {"Name", "City"},
        {{"Alice","New York"},{"Bob","Chicago"},{"Charlie","Houston"},{"Diana","Seattle"}}
    ),
    Joined = Table.FuzzyNestedJoin(
        Orders, "CustomerName",
        Customers, "Name",
        "CustomerMatches",
        JoinKind.LeftOuter,
        [Threshold = 0.75]
    )
in
    Joined
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Amount","type":"any"},{"name":"CustomerMatches","type":"table"}],"rows":[{"OrderID":"1","CustomerName":"Alise","Amount":"250","CustomerMatches":"[Table]"},{"OrderID":"2","CustomerName":"Bobb","Amount":"180","CustomerMatches":"[Table]"},{"OrderID":"3","CustomerName":"Charlei","Amount":"300","CustomerMatches":"[Table]"},{"OrderID":"4","CustomerName":"Diana","Amount":"150","CustomerMatches":"[Table]"}]}
-->

### Example 2: Expand the nested column to bring in City data

```powerquery
let
    Orders = #table({"OrderID","CustomerName","Amount"},{{1,"Alise",250},{2,"Bobb",180}}),
    Customers = #table({"Name","City","State"},{{"Alice","New York","NY"},{"Bob","Chicago","IL"}}),
    Joined  = Table.FuzzyNestedJoin(Orders,"CustomerName",Customers,"Name","CustomerMatches",JoinKind.LeftOuter,[Threshold=0.75]),
    Expanded = Table.ExpandTableColumn(Joined, "CustomerMatches", {"Name","City","State"}, {"CanonicalName","City","State"})
in
    Expanded
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Amount","type":"any"},{"name":"CanonicalName","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alise","Amount":"250","CanonicalName":"Alice","City":"New York","State":"NY"},{"OrderID":"2","CustomerName":"Bobb","Amount":"180","CanonicalName":"Bob","City":"Chicago","State":"IL"}]}
-->

### Example 3: Count fuzzy matches per order row

Use `Table.RowCount` on each nested table to see how many candidates matched.

```powerquery
let
    Orders    = #table({"OrderID","Product"},{{1,"Widge A"},{2,"Gadgit B"},{3,"Xyz"}}),
    Products  = #table({"CanonicalName"},{{"Widget A"},{"Widget C"},{"Gadget B"},{"Gadget D"}}),
    Joined    = Table.FuzzyNestedJoin(Orders,"Product",Products,"CanonicalName","Matches",JoinKind.LeftOuter,[Threshold=0.6]),
    WithCount = Table.AddColumn(Joined, "MatchCount", each Table.RowCount([Matches]), type number),
    Result    = Table.RemoveColumns(WithCount, {"Matches"})
in
    Result
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"Product","type":"any"},{"name":"MatchCount","type":"number"}],"rows":[{"OrderID":"1","Product":"Widge A","MatchCount":"2"},{"OrderID":"2","Product":"Gadgit B","MatchCount":"2"},{"OrderID":"3","Product":"Xyz","MatchCount":"0"}]}
-->
