---
title: "Table.FuzzyJoin"
slug: "table-fuzzyjoin"
category: "Table"
description: "Joins two tables using fuzzy (approximate) string matching on key columns."
syntax: "Table.FuzzyJoin(table1 as table, key1 as any, table2 as table, key2 as any, optional joinKind as nullable number, optional joinOptions as nullable record) as table"
returnType: "table"
returnDescription: "A table resulting from joining the two tables using fuzzy key matching."
parameters:
  - name: "table1"
    type: "table"
    required: true
    description: "The left table."
  - name: "key1"
    type: "any"
    required: true
    description: "The key column name or list of column names from table1."
  - name: "table2"
    type: "table"
    required: true
    description: "The right table."
  - name: "key2"
    type: "any"
    required: true
    description: "The key column name or list of column names from table2."
  - name: "joinKind"
    type: "number"
    required: false
    description: "Optional. The join type: JoinKind.Inner (0), JoinKind.LeftOuter (1), JoinKind.RightOuter (2), JoinKind.FullOuter (3), JoinKind.LeftAnti (4), JoinKind.RightAnti (5). Defaults to JoinKind.Inner."
  - name: "joinOptions"
    type: "record"
    required: false
    description: "Optional record supporting fields: Threshold (0.0–1.0 similarity), IgnoreCase, IgnoreSpace, NumberOfMatches, TransformationTable."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: false
  excelOnline: false
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-join"
  - "table-nestedjoin"
  - "table-fuzzynestedjoin"
  - "table-fuzzygroup"
---

## Remarks

`Table.FuzzyJoin` joins two tables using approximate string matching on key columns instead of exact equality. It tolerates typos, spacing differences, and case variations, making it useful when joining datasets from different sources where key values may not be standardized — such as customer names entered by hand, product descriptions from different vendors, or city names with varied spellings.

The `joinOptions` record supports these fields:

- `Threshold` (number, 0.0–1.0): minimum similarity for a match. Default `0.8`. Lower values match more loosely; `1.0` is exact matching only.
- `IgnoreCase` (logical): ignore case. Default `true`.
- `IgnoreSpace` (logical): ignore whitespace. Default `true`.
- `NumberOfMatches` (number): limit matches per left-table row. Default is all matches.
- `TransformationTable` (table with `From` and `To` columns): pre-map known variants before scoring.

`Table.FuzzyJoin` returns a flat joined table (unlike `Table.FuzzyNestedJoin`, which returns nested tables). It does not fold to data sources. The default join kind is `JoinKind.Inner` — use `JoinKind.LeftOuter` to retain unmatched left rows. Be cautious with low `Threshold` values on large tables as performance can degrade significantly.

## Examples

### Example 1: Match Sales customer names against a canonical Customers table

Some orders have slightly misspelled customer names. Use `Table.FuzzyJoin` to resolve them.

```powerquery
let
    SalesWithTypos = #table(
        {"OrderID", "CustomerName", "Amount"},
        {{1,"Alise",250},{2,"Bobb",180},{3,"Charlie",300},{4,"Dianah",150}}
    ),
    Customers = #table(
        {"Name", "City", "State"},
        {{"Alice","New York","NY"},{"Bob","Chicago","IL"},{"Charlie","Houston","TX"},{"Diana","Seattle","WA"}}
    )
in
    Table.FuzzyJoin(
        SalesWithTypos, "CustomerName",
        Customers,      "Name",
        JoinKind.LeftOuter,
        [Threshold = 0.75]
    )
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Amount","type":"any"},{"name":"Name","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alise","Amount":"250","Name":"Alice","City":"New York","State":"NY"},{"OrderID":"2","CustomerName":"Bobb","Amount":"180","Name":"Bob","City":"Chicago","State":"IL"},{"OrderID":"3","CustomerName":"Charlie","Amount":"300","Name":"Charlie","City":"Houston","State":"TX"},{"OrderID":"4","CustomerName":"Dianah","Amount":"150","Name":"Diana","City":"Seattle","State":"WA"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "SalesWithTypos",
      "description": "Defines an inline orders table with four rows where customer names contain typos (Alise, Bobb, Dianah) alongside their order amounts.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Amount","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alise","Amount":"250"},{"OrderID":"2","CustomerName":"Bobb","Amount":"180"},{"OrderID":"3","CustomerName":"Charlie","Amount":"300"},{"OrderID":"4","CustomerName":"Dianah","Amount":"150"}]}
    },
    {
      "name": "Customers",
      "description": "Defines a canonical Customers lookup table with correctly spelled names, cities, and states.",
      "output": {"columns":[{"name":"Name","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"Name":"Alice","City":"New York","State":"NY"},{"Name":"Bob","City":"Chicago","State":"IL"},{"Name":"Charlie","City":"Houston","State":"TX"},{"Name":"Diana","City":"Seattle","State":"WA"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FuzzyJoin matches each misspelled CustomerName to the closest canonical Name using a 0.75 similarity threshold, producing a flat joined table with city and state resolved.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Amount","type":"any"},{"name":"Name","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alise","Amount":"250","Name":"Alice","City":"New York","State":"NY"},{"OrderID":"2","CustomerName":"Bobb","Amount":"180","Name":"Bob","City":"Chicago","State":"IL"},{"OrderID":"3","CustomerName":"Charlie","Amount":"300","Name":"Charlie","City":"Houston","State":"TX"},{"OrderID":"4","CustomerName":"Dianah","Amount":"150","Name":"Diana","City":"Seattle","State":"WA"}]}
    }
  ]
}
-->

### Example 2: Use a TransformationTable to handle known aliases

Pre-map known mismatches via `TransformationTable` before fuzzy scoring takes over.

```powerquery
let
    Orders = #table({"CustomerRef","Total"},{{"Al","500"},{"Robbie","200"},{"Diane","350"}}),
    Customers = #table({"Name"},{{"Alice"},{"Bob"},{"Diana"}}),
    Mapping = #table({"From","To"},{{"Al","Alice"},{"Robbie","Bob"},{"Diane","Diana"}})
in
    Table.FuzzyJoin(
        Orders, "CustomerRef",
        Customers, "Name",
        JoinKind.LeftOuter,
        [Threshold = 0.5, TransformationTable = Mapping]
    )
```

<!--output
{"columns":[{"name":"CustomerRef","type":"any"},{"name":"Total","type":"any"},{"name":"Name","type":"any"}],"rows":[{"CustomerRef":"Al","Total":"500","Name":"Alice"},{"CustomerRef":"Robbie","Total":"200","Name":"Bob"},{"CustomerRef":"Diane","Total":"350","Name":"Diana"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Orders",
      "description": "Defines an inline Orders table with three rows using informal customer reference names (Al, Robbie, Diane) and their totals.",
      "output": {"columns":[{"name":"CustomerRef","type":"any"},{"name":"Total","type":"any"}],"rows":[{"CustomerRef":"Al","Total":"500"},{"CustomerRef":"Robbie","Total":"200"},{"CustomerRef":"Diane","Total":"350"}]}
    },
    {
      "name": "Customers",
      "description": "Defines a canonical Customers lookup table with three canonical names: Alice, Bob, Diana.",
      "output": {"columns":[{"name":"Name","type":"any"}],"rows":[{"Name":"Alice"},{"Name":"Bob"},{"Name":"Diana"}]}
    },
    {
      "name": "Mapping",
      "description": "Defines a TransformationTable that explicitly maps each informal alias to its canonical name before fuzzy scoring is applied.",
      "output": {"columns":[{"name":"From","type":"any"},{"name":"To","type":"any"}],"rows":[{"From":"Al","To":"Alice"},{"From":"Robbie","To":"Bob"},{"From":"Diane","To":"Diana"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FuzzyJoin applies the TransformationTable mappings first, then resolves each CustomerRef to a canonical Name with a left outer join.",
      "output": {"columns":[{"name":"CustomerRef","type":"any"},{"name":"Total","type":"any"},{"name":"Name","type":"any"}],"rows":[{"CustomerRef":"Al","Total":"500","Name":"Alice"},{"CustomerRef":"Robbie","Total":"200","Name":"Bob"},{"CustomerRef":"Diane","Total":"350","Name":"Diana"}]}
    }
  ]
}
-->

### Example 3: Limit to one match per left row with NumberOfMatches

Prevent one-to-many expansion by capping matches at 1.

```powerquery
Table.FuzzyJoin(
    #table({"Product"},{{"Widge A"},{"Gadgit B"}}),
    "Product",
    #table({"CanonicalName","Category"},{{"Widget A","Widgets"},{"Gadget B","Gadgets"}}),
    "CanonicalName",
    JoinKind.LeftOuter,
    [Threshold = 0.7, NumberOfMatches = 1]
)
```

<!--output
{"columns":[{"name":"Product","type":"any"},{"name":"CanonicalName","type":"any"},{"name":"Category","type":"any"}],"rows":[{"Product":"Widge A","CanonicalName":"Widget A","Category":"Widgets"},{"Product":"Gadgit B","CanonicalName":"Gadget B","Category":"Gadgets"}]}
-->
