---
title: "Table.RemoveFirstN"
slug: "table-removefirstn"
category: "Table"
description: "Removes the first N rows of a table, or rows while a condition is true."
syntax: "Table.RemoveFirstN(table as table, countOrCondition as any) as table"
returnType: "table"
returnDescription: "The table with the first N rows (or leading conditional rows) removed."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to remove rows from."
  - name: "countOrCondition"
    type: "any"
    required: true
    description: "A number specifying how many rows to remove, or a condition function that removes rows while it returns true."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-removelastn"
  - "table-removerows"
  - "table-skip"
  - "table-firstn"
---

## Remarks

`Table.RemoveFirstN` removes rows from the top of the table. When `countOrCondition` is a number, it removes exactly that many leading rows. When it is a function (predicate), it removes rows from the top while the condition returns `true` — stopping as soon as the first row that fails the condition is reached, and retaining all rows from that point forward.

This function is equivalent to `Table.Skip` when given a number. The condition-based form is particularly useful for stripping leading metadata rows from flat files — for example, removing header comment lines that appear before the actual data header, where the number of such lines may vary.

`Table.RemoveFirstN` does not fold to data sources. For large tables, it materializes the leading rows locally to evaluate the condition. If the leading rows to remove are identifiable at query design time, prefer `Table.Skip(n)` for slightly clearer intent.

## Examples

### Example 1: Remove the first 2 orders from the Sales table

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "Region"},
        {{1,"Alice","Widget A","East"},{2,"Bob","Gadget B","West"},
         {3,"Charlie","Widget C","East"},{4,"Diana","Widget A","North"}}
    )
in
    Table.RemoveFirstN(Sales, 2)
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"Region","type":"any"}],"rows":[{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C","Region":"East"},{"OrderID":"4","CustomerName":"Diana","Product":"Widget A","Region":"North"}]}
-->

### Example 2: Remove leading rows where the order date is in January

Remove rows while OrderDate is in January 2024, keeping rows from February onwards.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "OrderDate"},
        {{1,"Alice",#date(2024,1,15)},{2,"Bob",#date(2024,1,18)},{3,"Charlie",#date(2024,2,1)},{8,"Diana",#date(2024,4,15)}}
    )
in
    Table.RemoveFirstN(Sales, each Date.Month([OrderDate]) = 1)
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"OrderDate","type":"any"}],"rows":[{"OrderID":"3","CustomerName":"Charlie","OrderDate":"2024-02-01"},{"OrderID":"8","CustomerName":"Diana","OrderDate":"2024-04-15"}]}
-->

### Example 3: Strip leading comment rows from a flat-file import

```powerquery
let
    Raw = #table(
        {"Content"},
        {{"# Generated: 2024-01-01"},{"# Version: 2.0"},{"OrderID,Customer,Amount"},{"1,Alice,100"},{"2,Bob,200"}}
    )
in
    Table.RemoveFirstN(Raw, each Text.StartsWith([Content], "#"))
```

<!--output
{"columns":[{"name":"Content","type":"any"}],"rows":[{"Content":"OrderID,Customer,Amount"},{"Content":"1,Alice,100"},{"Content":"2,Bob,200"}]}
-->
