---
title: "Table.SingleRow"
slug: "table-singlerow"
category: "Table"
description: "Returns the single row of a table as a record. Throws an error if the table does not have exactly one row."
syntax: "Table.SingleRow(table as table) as record"
returnType: "record"
returnDescription: "The single row of the table as a record."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "A table that must contain exactly one row."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-first"
  - "table-last"
  - "table-firstvalue"
  - "table-selectrows"
---

## Remarks

`Table.SingleRow` asserts that a table contains exactly one row and returns that row as a record. If the table has zero rows or more than one row, an error is raised at runtime. This "fail loud" behavior makes it a deliberate assertion — use it when your query logic guarantees exactly one match and you want an explicit error rather than a silent null or the wrong row if the assumption is violated.

Typical use cases include: reading a unique configuration parameter after filtering by name, extracting a uniquely-identified record after a key lookup, or validating that a pre-filtered dataset contains exactly one result before processing it.

Choose `Table.SingleRow` over `Table.First` when the one-row constraint must be enforced. Choose `Table.First` with a default value when zero rows is an acceptable outcome. Choose `Table.FirstValue` when you only need the top-left scalar and don't need to guard against row count.

## Examples

### Example 1: Look up a specific customer by CustomerID

```powerquery
let
    Customers = #table(
        {"CustomerID","Name","Email","City","State"},
        {{1,"Alice","alice@example.com","New York","NY"},
         {2,"Bob","bob@example.com","Chicago","IL"},
         {3,"Charlie","charlie@example.com","Houston","TX"},
         {4,"Diana","diana@example.com","Seattle","WA"}}
    ),
    Filtered = Table.SelectRows(Customers, each [CustomerID] = 3)
in
    Table.SingleRow(Filtered)
```

<!--output
{"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[CustomerID = 3, Name = \"Charlie\", Email = \"charlie@example.com\", City = \"Houston\", State = \"TX\"]"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Customers",
      "description": "Defines a table with 4 customer rows containing CustomerID, Name, Email, City, and State columns.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Email","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","Email":"alice@example.com","City":"New York","State":"NY"},{"CustomerID":"2","Name":"Bob","Email":"bob@example.com","City":"Chicago","State":"IL"},{"CustomerID":"3","Name":"Charlie","Email":"charlie@example.com","City":"Houston","State":"TX"},{"CustomerID":"4","Name":"Diana","Email":"diana@example.com","City":"Seattle","State":"WA"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters Customers to keep only rows where CustomerID equals 3, producing a single-row table containing Charlie's record.",
      "output": {"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"Email","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"CustomerID":"3","Name":"Charlie","Email":"charlie@example.com","City":"Houston","State":"TX"}]}
    },
    {
      "name": "Result",
      "description": "The final output — asserts the filtered table has exactly one row and returns that row as a record.",
      "output": {"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[CustomerID = 3, Name = \"Charlie\", Email = \"charlie@example.com\", City = \"Houston\", State = \"TX\"]"}]}
    }
  ]
}
-->

### Example 2: Read a configuration value using field access on the single row

```powerquery
let
    Config = #table(
        {"Parameter","Value"},
        {{"DefaultRegion","East"},{"MaxOrders","500"},{"CurrencyCode","USD"}}
    ),
    Filtered = Table.SelectRows(Config, each [Parameter] = "CurrencyCode")
in
    Table.SingleRow(Filtered)[Value]
```

<!--output
{"columns":[{"name":"Result","type":"text"}],"rows":[{"Result":"USD"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Config",
      "description": "Defines a configuration table with 3 parameter rows containing Parameter and Value columns.",
      "output": {"columns":[{"name":"Parameter","type":"any"},{"name":"Value","type":"any"}],"rows":[{"Parameter":"DefaultRegion","Value":"East"},{"Parameter":"MaxOrders","Value":"500"},{"Parameter":"CurrencyCode","Value":"USD"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters Config to keep only the row where Parameter equals \"CurrencyCode\", producing a single-row table.",
      "output": {"columns":[{"name":"Parameter","type":"any"},{"name":"Value","type":"any"}],"rows":[{"Parameter":"CurrencyCode","Value":"USD"}]}
    },
    {
      "name": "Result",
      "description": "The final output — asserts exactly one row exists, returns it as a record, then extracts the Value field as a scalar text value.",
      "output": {"columns":[{"name":"Result","type":"text"}],"rows":[{"Result":"USD"}]}
    }
  ]
}
-->

### Example 3: Assert a product lookup returns exactly one result

```powerquery
let
    Products = #table(
        type table [ProductID = number, ProductName = text, Category = text, Price = number, InStock = logical],
        {{1,"Widget A","Widgets",25.00,true},{2,"Gadget B","Gadgets",50.00,true},
         {3,"Widget C","Widgets",15.00,false},{4,"Gadget D","Gadgets",75.00,true}}
    ),
    Filtered = Table.SelectRows(Products, each [ProductID] = 4)
in
    Table.SingleRow(Filtered)[Price]
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"75"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Defines a typed table with 4 products containing ProductID, ProductName, Category, Price, and InStock columns.",
      "output": {"columns":[{"name":"ProductID","type":"number"},{"name":"ProductName","type":"text"},{"name":"Category","type":"text"},{"name":"Price","type":"number"},{"name":"InStock","type":"logical"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets","Price":"25","InStock":"true"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets","Price":"50","InStock":"true"},{"ProductID":"3","ProductName":"Widget C","Category":"Widgets","Price":"15","InStock":"false"},{"ProductID":"4","ProductName":"Gadget D","Category":"Gadgets","Price":"75","InStock":"true"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters Products to keep only the row where ProductID equals 4, producing a single-row table containing Gadget D.",
      "output": {"columns":[{"name":"ProductID","type":"number"},{"name":"ProductName","type":"text"},{"name":"Category","type":"text"},{"name":"Price","type":"number"},{"name":"InStock","type":"logical"}],"rows":[{"ProductID":"4","ProductName":"Gadget D","Category":"Gadgets","Price":"75","InStock":"true"}]}
    },
    {
      "name": "Result",
      "description": "The final output — asserts exactly one row exists, returns it as a record, then extracts the Price field as a scalar number.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"75"}]}
    }
  ]
}
-->
