---
title: "Table.Partition"
slug: "table-partition"
category: "Table"
description: "Partitions a table into a list of tables using a hash function on a specified column."
syntax: "Table.Partition(table as table, column as text, groups as number, seed as number) as list"
returnType: "list"
returnDescription: "A list of tables, where each table is a partition of the original."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to partition."
  - name: "column"
    type: "text"
    required: true
    description: "The column whose values are hashed to assign rows to partitions."
  - name: "groups"
    type: "number"
    required: true
    description: "The number of partitions (output tables) to create."
  - name: "seed"
    type: "number"
    required: true
    description: "A seed value for the hash function, affecting how rows are distributed."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-split"
  - "table-splitat"
  - "table-selectrows"
---

## Remarks

`Table.Partition` distributes rows from a table into a list of `groups` sub-tables using a hash function applied to the specified `column`. Each row is assigned to exactly one partition based on a hash of its column value, modulo the number of groups. Every row in the original table appears in exactly one partition — no rows are dropped or duplicated.

The `seed` parameter influences the hash function and changes how rows are distributed across partitions. Changing `seed` with the same data and `groups` count may yield a different distribution. Partitioning is primarily used for parallel or chunked processing — for example, processing a large table in N independent batches, or distributing work across multiple calls.

`Table.Partition` is the counterpart of `Table.FromPartitions` — use `Table.FromPartitions` to reassemble partitioned tables back into one. For splitting a table into sequential pages by row count, use `Table.Split` instead.

## Examples

### Example 1: Partition 8 Sales rows into 3 buckets

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "Region"},
        {{1,"Alice","Widget A","East"},{2,"Bob","Gadget B","West"},{3,"Charlie","Widget C","East"},
         {4,"Alice","Gadget D","North"},{5,"Diana","Widget A","West"},{6,"Bob","Thingamajig E","East"},
         {7,"Charlie","Gadget B","West"},{8,"Diana","Widget C","North"}}
    ),
    Partitions = Table.Partition(Sales, "OrderID", 3, 0)
in
    List.Count(Partitions)
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"3"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 8 orders containing OrderID, CustomerName, Product, and Region columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"Region","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A","Region":"East"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B","Region":"West"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C","Region":"East"},{"OrderID":"4","CustomerName":"Alice","Product":"Gadget D","Region":"North"},{"OrderID":"5","CustomerName":"Diana","Product":"Widget A","Region":"West"},{"OrderID":"6","CustomerName":"Bob","Product":"Thingamajig E","Region":"East"},{"OrderID":"7","CustomerName":"Charlie","Product":"Gadget B","Region":"West"},{"OrderID":"8","CustomerName":"Diana","Product":"Widget C","Region":"North"}]}
    },
    {
      "name": "Partitions",
      "description": "Splits the Sales table into 3 hash-based partitions by OrderID with seed 0, producing a list of 3 sub-tables that together contain all 8 rows.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"Table 1"},{"Value":"Table 2"},{"Value":"Table 3"}]}
    },
    {
      "name": "Result",
      "description": "The final output — counts the number of partitions in the list, confirming that 3 sub-tables were created.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"3"}]}
    }
  ]
}
-->

### Example 2: Access and count rows in each partition

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName"},
        {{1,"Alice"},{2,"Bob"},{3,"Charlie"},{4,"Alice"},{5,"Diana"},{6,"Bob"},{7,"Charlie"},{8,"Diana"}}
    ),
    Partitions = Table.Partition(Sales, "OrderID", 2, 0),
    Counts     = List.Transform(Partitions, Table.RowCount)
in
    Counts
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{4, 4}"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 8 orders containing OrderID and CustomerName columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice"},{"OrderID":"2","CustomerName":"Bob"},{"OrderID":"3","CustomerName":"Charlie"},{"OrderID":"4","CustomerName":"Alice"},{"OrderID":"5","CustomerName":"Diana"},{"OrderID":"6","CustomerName":"Bob"},{"OrderID":"7","CustomerName":"Charlie"},{"OrderID":"8","CustomerName":"Diana"}]}
    },
    {
      "name": "Partitions",
      "description": "Splits the Sales table into 2 hash-based partitions by OrderID with seed 0, producing a list of 2 sub-tables each containing 4 rows.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"Table 1 (4 rows)"},{"Value":"Table 2 (4 rows)"}]}
    },
    {
      "name": "Counts",
      "description": "The final output — applies Table.RowCount to each partition, returning a list of row counts for each sub-table.",
      "output": {"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{4, 4}"}]}
    }
  ]
}
-->

### Example 3: Process each partition independently and recombine

```powerquery
let
    Employees = #table(
        type table [EmployeeID = text, FullName = text, Salary = number],
        {{"E001","alice smith",55000},{"E002","BOB JONES",95000},{"E003","Charlie Brown",72000},
         {"E004","diana PRINCE",68000},{"E005","Eve Martinez",88000},{"E006","frank lee",52000}}
    ),
    Partitions = Table.Partition(Employees, "EmployeeID", 2, 0),
    Processed  = List.Transform(Partitions, each Table.AddColumn(_, "Bonus", each [Salary] * 0.10, type number)),
    Combined   = Table.Combine(Processed)
in
    Combined
```

<!--output
{"columns":[{"name":"EmployeeID","type":"text"},{"name":"FullName","type":"text"},{"name":"Salary","type":"number"},{"name":"Bonus","type":"number"}],"rows":[{"EmployeeID":"E002","FullName":"BOB JONES","Salary":"95000","Bonus":"9500"},{"EmployeeID":"E004","FullName":"diana PRINCE","Salary":"68000","Bonus":"6800"},{"EmployeeID":"E006","FullName":"frank lee","Salary":"52000","Bonus":"5200"},{"EmployeeID":"E001","FullName":"alice smith","Salary":"55000","Bonus":"5500"},{"EmployeeID":"E003","FullName":"Charlie Brown","Salary":"72000","Bonus":"7200"},{"EmployeeID":"E005","FullName":"Eve Martinez","Salary":"88000","Bonus":"8800"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Employees",
      "description": "Defines a typed table with 6 employee records containing EmployeeID, FullName, and Salary columns.",
      "output": {"columns":[{"name":"EmployeeID","type":"text"},{"name":"FullName","type":"text"},{"name":"Salary","type":"number"}],"rows":[{"EmployeeID":"E001","FullName":"alice smith","Salary":"55000"},{"EmployeeID":"E002","FullName":"BOB JONES","Salary":"95000"},{"EmployeeID":"E003","FullName":"Charlie Brown","Salary":"72000"},{"EmployeeID":"E004","FullName":"diana PRINCE","Salary":"68000"},{"EmployeeID":"E005","FullName":"Eve Martinez","Salary":"88000"},{"EmployeeID":"E006","FullName":"frank lee","Salary":"52000"}]}
    },
    {
      "name": "Partitions",
      "description": "Splits the Employees table into 2 hash-based partitions by EmployeeID with seed 0, producing a list of 2 sub-tables.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"Table 1 (3 rows: E002, E004, E006)"},{"Value":"Table 2 (3 rows: E001, E003, E005)"}]}
    },
    {
      "name": "Processed",
      "description": "Applies Table.AddColumn to each partition, adding a Bonus column calculated as 10% of Salary for every employee.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"Table 1 with Bonus (3 rows)"},{"Value":"Table 2 with Bonus (3 rows)"}]}
    },
    {
      "name": "Combined",
      "description": "The final output — combines all processed partition tables into one table with all 6 employees and their computed bonuses.",
      "output": {"columns":[{"name":"EmployeeID","type":"text"},{"name":"FullName","type":"text"},{"name":"Salary","type":"number"},{"name":"Bonus","type":"number"}],"rows":[{"EmployeeID":"E002","FullName":"BOB JONES","Salary":"95000","Bonus":"9500"},{"EmployeeID":"E004","FullName":"diana PRINCE","Salary":"68000","Bonus":"6800"},{"EmployeeID":"E006","FullName":"frank lee","Salary":"52000","Bonus":"5200"},{"EmployeeID":"E001","FullName":"alice smith","Salary":"55000","Bonus":"5500"},{"EmployeeID":"E003","FullName":"Charlie Brown","Salary":"72000","Bonus":"7200"},{"EmployeeID":"E005","FullName":"Eve Martinez","Salary":"88000","Bonus":"8800"}]}
    }
  ]
}
-->
