---
title: "Table.FromRows"
slug: "table-fromrows"
category: "Table"
description: "Constructs a table from a list of row lists, with optional column names or types."
syntax: "Table.FromRows(rows as list, optional columns as any) as table"
returnType: "table"
returnDescription: "A table built from the provided list of row value lists."
parameters:
  - name: "rows"
    type: "list"
    required: true
    description: "A list of lists, where each inner list represents a row of values."
  - name: "columns"
    type: "any"
    required: false
    description: "Optional. A list of column names, a table type, or a list of {name, type} pairs defining column names and types."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-fromrecords"
  - "table-fromcolumns"
  - "table-fromlist"
---

## Remarks

`Table.FromRows` constructs a table from a list of lists, where each inner list represents one row of values positionally mapped to columns. It is one of the most common ways to create small inline tables in Power Query — for lookup tables, test data, parameter sets, or reference values embedded directly in a query.

The `columns` parameter controls column naming and typing and accepts three forms:
- **Omitted**: columns are named `Column1`, `Column2`, etc., typed as `any`.
- **List of strings**: `{"Name", "Score"}` — sets column names, types remain `any`.
- **Table type**: `type table [Name = text, Score = number]` — sets both names and types. This is the recommended form for production queries because it ensures downstream type safety and enables accurate schema documentation.

Prefer `#table(type table [...], {...})` shorthand for brevity in expressions where the table type is known at authoring time — it is equivalent to `Table.FromRows` with a type argument but more concise.

## Examples

### Example 1: Create an inline lookup table with named columns

```powerquery
Table.FromRows(
    {
        {1, "Alice", "New York", "NY"},
        {2, "Bob",   "Chicago",  "IL"},
        {3, "Charlie","Houston", "TX"},
        {4, "Diana", "Seattle",  "WA"}
    },
    {"CustomerID", "Name", "City", "State"}
)
```

<!--output
{"columns":[{"name":"CustomerID","type":"any"},{"name":"Name","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"CustomerID":"1","Name":"Alice","City":"New York","State":"NY"},{"CustomerID":"2","Name":"Bob","City":"Chicago","State":"IL"},{"CustomerID":"3","Name":"Charlie","City":"Houston","State":"TX"},{"CustomerID":"4","Name":"Diana","City":"Seattle","State":"WA"}]}
-->

### Example 2: Create a typed table for schema-safe downstream use

Specifying a table type ensures columns carry proper types, which matters for folding and downstream transformations.

```powerquery
Table.FromRows(
    {{1,"Widget A","Widgets",25.00,true},{2,"Gadget B","Gadgets",50.00,true},{3,"Widget C","Widgets",15.00,false}},
    type table [ProductID = number, ProductName = text, Category = text, Price = number, InStock = logical]
)
```

<!--output
{"columns":[{"name":"ProductID","type":"number"},{"name":"ProductName","type":"text"},{"name":"Category","type":"text"},{"name":"Price","type":"number"},{"name":"InStock","type":"logical"}],"rows":[{"ProductID":"1","ProductName":"Widget A","Category":"Widgets","Price":"25","InStock":"true"},{"ProductID":"2","ProductName":"Gadget B","Category":"Gadgets","Price":"50","InStock":"true"},{"ProductID":"3","ProductName":"Widget C","Category":"Widgets","Price":"15","InStock":"false"}]}
-->

### Example 3: Build a table from a dynamically generated list of rows

Combine `Table.FromRows` with `List.Transform` to construct a table from computed values.

```powerquery
let
    Products = #table({"ProductName","Price"},{{"Widget A",25.00},{"Gadget B",50.00},{"Widget C",15.00}}),
    Rows     = List.Transform(
                   Table.ToRows(Products),
                   each {_{0}, _{1}, _{1} * 1.1}
               )
in
    Table.FromRows(Rows, {"ProductName", "Price", "PriceWithTax"})
```

<!--output
{"columns":[{"name":"ProductName","type":"any"},{"name":"Price","type":"any"},{"name":"PriceWithTax","type":"any"}],"rows":[{"ProductName":"Widget A","Price":"25","PriceWithTax":"27.5"},{"ProductName":"Gadget B","Price":"50","PriceWithTax":"55"},{"ProductName":"Widget C","Price":"15","PriceWithTax":"16.5"}]}
-->
