---
title: "Table.PositionOfAny"
slug: "table-positionofany"
category: "Table"
description: "Returns the first position of any row in the table that matches any record in the given list."
syntax: "Table.PositionOfAny(table as table, rows as list, optional occurrence as nullable number, optional equationCriteria as any) as any"
returnType: "any"
returnDescription: "A row index, a list of row indices, or -1 if no match is found."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to search."
  - name: "rows"
    type: "list"
    required: true
    description: "A list of records to search for."
  - name: "occurrence"
    type: "number"
    required: false
    description: "Optional. Use Occurrence.First (0), Occurrence.Last (1), or Occurrence.All (2) to control which positions are returned."
  - name: "equationCriteria"
    type: "any"
    required: false
    description: "Optional. Column name(s) or comparer to restrict which fields are compared."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-positionof"
  - "table-containsany"
  - "table-selectrows"
---

## Remarks

`Table.PositionOfAny` is the multi-candidate variant of `Table.PositionOf`. Instead of searching for a single record, it accepts a list of candidate records and returns the position of the first row in the table that matches any of them. If no candidate matches any row, it returns `-1`.

The `occurrence` parameter controls the return behavior:
- `Occurrence.First` (default): the index of the first row matching any candidate.
- `Occurrence.Last`: the index of the last row matching any candidate.
- `Occurrence.All`: a list of all row indices that match any candidate.

The optional `equationCriteria` parameter restricts which columns are compared, enabling partial record matching across all candidates simultaneously. This function is useful when you have a set of "sentinel" or "anchor" rows whose positions you need to locate, for example to determine slice boundaries in a structured flat file.

## Examples

### Example 1: Find the first position of any of several customers

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product"},
        {{1,"Alice","Widget A"},{2,"Bob","Gadget B"},{3,"Charlie","Widget C"},{4,"Diana","Gadget D"}}
    ),
    Targets = {[CustomerName = "Charlie"], [CustomerName = "Diana"]}
in
    Table.PositionOfAny(Sales, Targets, Occurrence.First, "CustomerName")
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"2"}]}
-->

### Example 2: No candidate matches — returns -1

```powerquery
let
    Products = #table(
        {"ProductName"},
        {{"Widget A"},{"Gadget B"},{"Widget C"}}
    ),
    Searches = {[ProductName = "Thingamajig E"], [ProductName = "Widget Z"]}
in
    Table.PositionOfAny(Products, Searches, Occurrence.First, "ProductName")
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"-1"}]}
-->

### Example 3: Return all positions matching any of the target customers

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName"},
        {{1,"Alice"},{2,"Bob"},{3,"Alice"},{4,"Charlie"},{5,"Diana"},{6,"Bob"},{7,"Alice"}}
    ),
    Targets = {[CustomerName = "Alice"], [CustomerName = "Bob"]}
in
    Table.PositionOfAny(Sales, Targets, Occurrence.All, "CustomerName")
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{0, 1, 2, 5, 6}"}]}
-->
