---
title: "Table.AddJoinColumn"
slug: "table-addjoincolumn"
category: "Table"
description: "Adds a column of nested tables from a second table by matching each row by key."
syntax: "Table.AddJoinColumn(table1 as table, key1 as any, table2 as function, key2 as any, newColumnName as text) as table"
returnType: "table"
returnDescription: "The original table with a new column containing nested tables of matching rows from table2."
parameters:
  - name: "table1"
    type: "table"
    required: true
    description: "The left table to add a column to."
  - name: "key1"
    type: "any"
    required: true
    description: "A column name or list of column names from table1 used as the join key."
  - name: "table2"
    type: "function"
    required: true
    description: "A function or table providing the right-side data to match against."
  - name: "key2"
    type: "any"
    required: true
    description: "A column name or list of column names from table2 used as the join key."
  - name: "newColumnName"
    type: "text"
    required: true
    description: "The name for the new nested table column."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-nestedjoin"
  - "table-join"
  - "table-expandtablecolumn"
  - "table-addjoincolumn"
---

## Remarks

`Table.AddJoinColumn` adds a column of nested tables to `table1` by matching each row's key against `table2`. The `table2` parameter is typed as `function` in the signature because this function was designed for custom connector scenarios where the right-side data may be a function invoked per key rather than a static table. In practice, you can pass an actual table and the function behaves like a left outer nested join.

For standard table-to-table joins in Power Query, `Table.NestedJoin` is preferred because it is more legible and has the same semantics. Reserve `Table.AddJoinColumn` for situations where the data connector pattern requires it, such as when building a connector that pages right-side data on demand.

Each cell in the new nested column contains a table of all matching rows from `table2`. Use `Table.ExpandTableColumn` to flatten these nested tables into additional columns on `table1`. Rows with no match produce an empty nested table (not null), so the expansion yields no rows for that key rather than an error.

## Examples

### Example 1: Add a nested join column using Sales and Customers

Each Sales row gets a nested table of matching Customer records.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "UnitPrice"},
        {
            {1, "Alice", "Widget A", 25.00},
            {2, "Bob",   "Gadget B", 50.00},
            {3, "Alice", "Widget C", 15.00}
        }
    ),
    Customers = #table(
        {"Name", "City"},
        {{"Alice", "New York"}, {"Bob", "Chicago"}}
    ),
    Result = Table.AddJoinColumn(Sales, "CustomerName", Customers, "Name", "CustomerInfo")
in
    Result
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"CustomerInfo","type":"table"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A","UnitPrice":"25","CustomerInfo":"[Table]"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B","UnitPrice":"50","CustomerInfo":"[Table]"},{"OrderID":"3","CustomerName":"Alice","Product":"Widget C","UnitPrice":"15","CustomerInfo":"[Table]"}]}
-->

### Example 2: Expand the nested column to get city data

After adding the join column, expand to pull the City field into the flat result.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName"},
        {{1, "Alice"}, {2, "Bob"}, {3, "Charlie"}}
    ),
    Customers = #table(
        {"Name", "City", "State"},
        {{"Alice", "New York", "NY"}, {"Bob", "Chicago", "IL"}, {"Charlie", "Houston", "TX"}}
    ),
    Joined   = Table.AddJoinColumn(Sales, "CustomerName", Customers, "Name", "CustomerInfo"),
    Expanded = Table.ExpandTableColumn(Joined, "CustomerInfo", {"City", "State"})
in
    Expanded
```

<!--output
{"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"City","type":"any"},{"name":"State","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","City":"New York","State":"NY"},{"OrderID":"2","CustomerName":"Bob","City":"Chicago","State":"IL"},{"OrderID":"3","CustomerName":"Charlie","City":"Houston","State":"TX"}]}
-->

### Example 3: Join on multiple key columns

Supply a list for both `key1` and `key2` to match on composite keys.

```powerquery
let
    Orders = #table(
        {"Region", "Product", "Qty"},
        {{"East", "Widget A", 4}, {"West", "Gadget B", 2}}
    ),
    Prices = #table(
        {"Region", "Product", "Price"},
        {{"East", "Widget A", 25.00}, {"West", "Gadget B", 50.00}}
    ),
    Result = Table.AddJoinColumn(Orders, {"Region", "Product"}, Prices, {"Region", "Product"}, "PriceInfo")
in
    Result
```

<!--output
{"columns":[{"name":"Region","type":"any"},{"name":"Product","type":"any"},{"name":"Qty","type":"any"},{"name":"PriceInfo","type":"table"}],"rows":[{"Region":"East","Product":"Widget A","Qty":"4","PriceInfo":"[Table]"},{"Region":"West","Product":"Gadget B","Qty":"2","PriceInfo":"[Table]"}]}
-->
