---
title: "Table.First"
slug: "table-first"
category: "Table"
description: "Returns the first row of the table as a record, or a default value if the table is empty."
syntax: "Table.First(table as table, optional default as nullable any) as any"
returnType: "any"
returnDescription: "The first row as a record, or the default value if the table is empty."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to retrieve the first row from."
  - name: "default"
    type: "any"
    required: false
    description: "Optional value to return if the table is empty. Defaults to null if omitted."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-last"
  - "table-firstn"
  - "table-firstvalue"
  - "table-singlerow"
---

## Remarks

`Table.First` returns the first row of a table as a record, enabling field access via `[FieldName]` syntax. If the table is empty and no `default` value is specified, the function returns `null`. Providing a default record prevents null propagation errors in downstream steps when the table might occasionally be empty — for example, after a filter that may match zero rows.

`Table.First` is commonly used after filtering to extract a single expected result (e.g., looking up a configuration value or getting the most recent transaction after sorting). For cases where you need to enforce that exactly one row exists, use `Table.SingleRow` instead, which will raise an error if the table has zero or more than one row. For reading just the top-left scalar value without unpacking a record, `Table.FirstValue` is more concise.

After sorting, `Table.First` efficiently returns the top row without materializing the entire sorted result into memory — the engine can short-circuit the evaluation. However, `Table.First` alone (without a prior sort) returns whichever row happens to be first in the table's current order, which may not be deterministic for database sources.

## Examples

### Example 1: Get the earliest order from the Sales table

Sort by OrderDate first, then retrieve the first row.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "UnitPrice", "Quantity", "OrderDate", "Region"},
        {{1,"Alice","Widget A",25.00,4,#date(2024,1,15),"East"},
         {2,"Bob","Gadget B",50.00,2,#date(2024,1,18),"West"},
         {3,"Charlie","Widget C",15.00,10,#date(2024,2,1),"East"}}
    ),
    Sorted = Table.Sort(Sales, {{"OrderDate", Order.Ascending}})
in
    Table.First(Sorted)
```

<!--output
{"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 1, CustomerName = \"Alice\", Product = \"Widget A\", UnitPrice = 25, Quantity = 4, OrderDate = #date(2024,1,15), Region = \"East\"]"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines an inline Sales table with three orders containing OrderID, CustomerName, Product, UnitPrice, Quantity, OrderDate, and Region columns.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Product","type":"text"},{"name":"UnitPrice","type":"number"},{"name":"Quantity","type":"number"},{"name":"OrderDate","type":"date"},{"name":"Region","type":"text"}],"rows":[{"OrderID":1,"CustomerName":"Alice","Product":"Widget A","UnitPrice":25,"Quantity":4,"OrderDate":"2024-01-15","Region":"East"},{"OrderID":2,"CustomerName":"Bob","Product":"Gadget B","UnitPrice":50,"Quantity":2,"OrderDate":"2024-01-18","Region":"West"},{"OrderID":3,"CustomerName":"Charlie","Product":"Widget C","UnitPrice":15,"Quantity":10,"OrderDate":"2024-02-01","Region":"East"}]}
    },
    {
      "name": "Sorted",
      "description": "Sorts the Sales table by OrderDate ascending so the earliest order appears first.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Product","type":"text"},{"name":"UnitPrice","type":"number"},{"name":"Quantity","type":"number"},{"name":"OrderDate","type":"date"},{"name":"Region","type":"text"}],"rows":[{"OrderID":1,"CustomerName":"Alice","Product":"Widget A","UnitPrice":25,"Quantity":4,"OrderDate":"2024-01-15","Region":"East"},{"OrderID":2,"CustomerName":"Bob","Product":"Gadget B","UnitPrice":50,"Quantity":2,"OrderDate":"2024-01-18","Region":"West"},{"OrderID":3,"CustomerName":"Charlie","Product":"Widget C","UnitPrice":15,"Quantity":10,"OrderDate":"2024-02-01","Region":"East"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.First returns the first row of the sorted table as a record, which corresponds to the earliest order.",
      "output": {"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 1, CustomerName = \"Alice\", Product = \"Widget A\", UnitPrice = 25, Quantity = 4, OrderDate = #date(2024,1,15), Region = \"East\"]"}]}
    }
  ]
}
-->

### Example 2: Extract a specific field from the first row

Chain field access directly onto `Table.First` to get a scalar value.

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product", "UnitPrice"},
        {{1,"Alice","Widget A",25.00},{2,"Bob","Gadget B",50.00}}
    ),
    Sorted = Table.Sort(Sales, {{"UnitPrice", Order.Descending}})
in
    Table.First(Sorted)[Product]
```

<!--output
{"columns":[{"name":"Result","type":"text"}],"rows":[{"Result":"Gadget B"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines an inline Sales table with two orders containing OrderID, CustomerName, Product, and UnitPrice columns.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Product","type":"text"},{"name":"UnitPrice","type":"number"}],"rows":[{"OrderID":1,"CustomerName":"Alice","Product":"Widget A","UnitPrice":25},{"OrderID":2,"CustomerName":"Bob","Product":"Gadget B","UnitPrice":50}]}
    },
    {
      "name": "Sorted",
      "description": "Sorts the Sales table by UnitPrice descending so the most expensive product appears first.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Product","type":"text"},{"name":"UnitPrice","type":"number"}],"rows":[{"OrderID":2,"CustomerName":"Bob","Product":"Gadget B","UnitPrice":50},{"OrderID":1,"CustomerName":"Alice","Product":"Widget A","UnitPrice":25}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.First returns the top row as a record and [Product] accesses its Product field, yielding the most expensive product name.",
      "output": {"columns":[{"name":"Result","type":"text"}],"rows":[{"Result":"Gadget B"}]}
    }
  ]
}
-->

### Example 3: Return a safe default when the filter matches no rows

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Region"},
        {{1,"Alice","East"},{2,"Bob","West"}}
    ),
    Filtered = Table.SelectRows(Sales, each [Region] = "North")
in
    Table.First(Filtered, [OrderID = 0, CustomerName = "None", Region = "N/A"])
```

<!--output
{"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 0, CustomerName = \"None\", Region = \"N/A\"]"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines an inline Sales table with two rows containing OrderID, CustomerName, and Region columns.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Region","type":"text"}],"rows":[{"OrderID":1,"CustomerName":"Alice","Region":"East"},{"OrderID":2,"CustomerName":"Bob","Region":"West"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters the table to keep only rows where Region equals \"North\", which matches no rows and produces an empty table.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Region","type":"text"}],"rows":[]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.First on the empty filtered table returns the supplied default record since there are no rows to return.",
      "output": {"columns":[{"name":"Result","type":"record"}],"rows":[{"Result":"[OrderID = 0, CustomerName = \"None\", Region = \"N/A\"]"}]}
    }
  ]
}
-->
