---
title: "Table.PositionOfAny"
slug: "table-positionofany"
category: "Table"
description: "Returns the first position of any row in the table that matches any record in the given list."
syntax: "Table.PositionOfAny(table as table, rows as list, optional occurrence as nullable number, optional equationCriteria as any) as any"
returnType: "any"
returnDescription: "A row index, a list of row indices, or -1 if no match is found."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to search."
  - name: "rows"
    type: "list"
    required: true
    description: "A list of records to search for."
  - name: "occurrence"
    type: "number"
    required: false
    description: "Optional. Use Occurrence.First (0), Occurrence.Last (1), or Occurrence.All (2) to control which positions are returned."
  - name: "equationCriteria"
    type: "any"
    required: false
    description: "Optional. Column name(s) or comparer to restrict which fields are compared."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-positionof"
  - "table-containsany"
  - "table-selectrows"
---

## Remarks

`Table.PositionOfAny` is the multi-candidate variant of `Table.PositionOf`. Instead of searching for a single record, it accepts a list of candidate records and returns the position of the first row in the table that matches any of them. If no candidate matches any row, it returns `-1`.

The `occurrence` parameter controls the return behavior:
- `Occurrence.First` (default): the index of the first row matching any candidate.
- `Occurrence.Last`: the index of the last row matching any candidate.
- `Occurrence.All`: a list of all row indices that match any candidate.

The optional `equationCriteria` parameter restricts which columns are compared, enabling partial record matching across all candidates simultaneously. This function is useful when you have a set of "sentinel" or "anchor" rows whose positions you need to locate, for example to determine slice boundaries in a structured flat file.

## Examples

### Example 1: Find the first position of any of several customers

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName", "Product"},
        {{1,"Alice","Widget A"},{2,"Bob","Gadget B"},{3,"Charlie","Widget C"},{4,"Diana","Gadget D"}}
    ),
    Targets = {[CustomerName = "Charlie"], [CustomerName = "Diana"]}
in
    Table.PositionOfAny(Sales, Targets, Occurrence.First, "CustomerName")
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"2"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 4 orders containing OrderID, CustomerName, and Product columns.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice","Product":"Widget A"},{"OrderID":"2","CustomerName":"Bob","Product":"Gadget B"},{"OrderID":"3","CustomerName":"Charlie","Product":"Widget C"},{"OrderID":"4","CustomerName":"Diana","Product":"Gadget D"}]}
    },
    {
      "name": "Targets",
      "description": "Defines a list of two records to search for — rows where CustomerName is \"Charlie\" or \"Diana\".",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"[CustomerName = \"Charlie\"]"},{"Value":"[CustomerName = \"Diana\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns the zero-based index of the first row in Sales matching any target by CustomerName, which is row 2 (Charlie).",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"2"}]}
    }
  ]
}
-->

### Example 2: No candidate matches — returns -1

```powerquery
let
    Products = #table(
        {"ProductName"},
        {{"Widget A"},{"Gadget B"},{"Widget C"}}
    ),
    Searches = {[ProductName = "Thingamajig E"], [ProductName = "Widget Z"]}
in
    Table.PositionOfAny(Products, Searches, Occurrence.First, "ProductName")
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"-1"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Defines a table with 3 product names in a single ProductName column.",
      "output": {"columns":[{"name":"ProductName","type":"any"}],"rows":[{"ProductName":"Widget A"},{"ProductName":"Gadget B"},{"ProductName":"Widget C"}]}
    },
    {
      "name": "Searches",
      "description": "Defines a list of two records to search for — rows where ProductName is \"Thingamajig E\" or \"Widget Z\".",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"[ProductName = \"Thingamajig E\"]"},{"Value":"[ProductName = \"Widget Z\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns -1 because neither \"Thingamajig E\" nor \"Widget Z\" appears in the Products table.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"-1"}]}
    }
  ]
}
-->

### Example 3: Return all positions matching any of the target customers

```powerquery
let
    Sales = #table(
        {"OrderID", "CustomerName"},
        {{1,"Alice"},{2,"Bob"},{3,"Alice"},{4,"Charlie"},{5,"Diana"},{6,"Bob"},{7,"Alice"}}
    ),
    Targets = {[CustomerName = "Alice"], [CustomerName = "Bob"]}
in
    Table.PositionOfAny(Sales, Targets, Occurrence.All, "CustomerName")
```

<!--output
{"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{0, 1, 2, 5, 6}"}]}
-->

<!--steps
{
  "steps": [
    {
      "name": "Sales",
      "description": "Defines a table with 7 orders where Alice appears at rows 0, 2, 6 and Bob appears at rows 1 and 5.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"}],"rows":[{"OrderID":"1","CustomerName":"Alice"},{"OrderID":"2","CustomerName":"Bob"},{"OrderID":"3","CustomerName":"Alice"},{"OrderID":"4","CustomerName":"Charlie"},{"OrderID":"5","CustomerName":"Diana"},{"OrderID":"6","CustomerName":"Bob"},{"OrderID":"7","CustomerName":"Alice"}]}
    },
    {
      "name": "Targets",
      "description": "Defines a list of two records to search for — rows where CustomerName is \"Alice\" or \"Bob\".",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"[CustomerName = \"Alice\"]"},{"Value":"[CustomerName = \"Bob\"]"}]}
    },
    {
      "name": "Result",
      "description": "The final output — returns a list of all zero-based row indices in Sales where CustomerName matches Alice (0, 2, 6) or Bob (1, 5).",
      "output": {"columns":[{"name":"Result","type":"list"}],"rows":[{"Result":"{0, 1, 2, 5, 6}"}]}
    }
  ]
}
-->
