---
title: "Table.FuzzyGroup"
slug: "table-fuzzygroup"
category: "Table"
description: "Groups rows using fuzzy matching on key column(s), tolerating typos and spelling variations."
syntax: "Table.FuzzyGroup(table as table, key as any, aggregatedColumns as list, optional options as nullable record) as table"
returnType: "table"
returnDescription: "A grouped table where similar key values are clustered together."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to group."
  - name: "key"
    type: "any"
    required: true
    description: "A column name or list of column names to group by using fuzzy matching."
  - name: "aggregatedColumns"
    type: "list"
    required: true
    description: "A list of {newColumnName, aggregationFunction} or {newColumnName, aggregationFunction, newColumnType} triples defining aggregated output columns."
  - name: "options"
    type: "record"
    required: false
    description: "Optional record with fuzzy options: Threshold, IgnoreCase, IgnoreSpace, NumberOfMatches, TransformationTable."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: false
  excelOnline: false
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-group"
  - "table-fuzzyjoin"
  - "table-addfuzzyclustercolumn"
  - "table-distinct"
---

## Remarks

`Table.FuzzyGroup` is a fuzzy-matching counterpart to `Table.Group`. Instead of requiring exact equality on key columns, it clusters rows with similar key values together — handling typos, case differences, extra spaces, and minor spelling variations. For example, `"Micosoft"`, `"Microsoft"`, and `"MICROSOFT"` would all be grouped under a single canonical representative.

The representative value chosen for each cluster is typically the first or most frequent form encountered. The `options` record supports the following fields:

- `Threshold` (number, 0.0–1.0): the minimum similarity score required for a match. Default is `0.8`. Lower values match more loosely; `1.0` requires exact equality.
- `IgnoreCase` (logical): ignore case differences. Default `true`.
- `IgnoreSpace` (logical): ignore whitespace differences. Default `true`.
- `NumberOfMatches` (number): maximum right-side matches per cluster group.
- `TransformationTable` (table): a custom mapping table with `From` and `To` columns to explicitly map known variants before fuzzy matching.

For inspecting cluster assignments without aggregating, use `Table.AddFuzzyClusterColumn` instead. `Table.FuzzyGroup` does not fold to data sources. On large datasets, consider pre-filtering to reduce the candidate space before applying fuzzy operations.

## Examples

### Example 1: Consolidate misspelled customer names and sum their orders

```powerquery
let
    Orders = #table(
        {"CustomerName", "Amount"},
        {{"Alice", 250}, {"Alise", 180}, {"Bob", 400}, {"Bobb", 120}, {"Charlie", 300}}
    )
in
    Table.FuzzyGroup(
        Orders,
        "CustomerName",
        {{"TotalAmount", List.Sum, type number}, {"OrderCount", List.Count, type number}},
        [Threshold = 0.8, IgnoreCase = true]
    )
```

<!--output
{"columns":[{"name":"CustomerName","type":"any"},{"name":"TotalAmount","type":"number"},{"name":"OrderCount","type":"number"}],"rows":[{"CustomerName":"Alice","TotalAmount":"430","OrderCount":"2"},{"CustomerName":"Bob","TotalAmount":"520","OrderCount":"2"},{"CustomerName":"Charlie","TotalAmount":"300","OrderCount":"1"}]}
-->

### Example 2: Use a TransformationTable to handle known brand variants

A `TransformationTable` with `From` and `To` columns maps known aliases before fuzzy scoring.

```powerquery
let
    Orders = #table(
        {"Vendor", "Spend"},
        {{"Microsoft", 500}, {"MS Corp", 200}, {"Google", 300}, {"Alphabet", 150}}
    ),
    Mapping = #table({"From","To"},{{"MS Corp","Microsoft"},{"Alphabet","Google"}})
in
    Table.FuzzyGroup(
        Orders,
        "Vendor",
        {{"TotalSpend", List.Sum, type number}},
        [Threshold = 0.6, TransformationTable = Mapping]
    )
```

<!--output
{"columns":[{"name":"Vendor","type":"any"},{"name":"TotalSpend","type":"number"}],"rows":[{"Vendor":"Microsoft","TotalSpend":"700"},{"Vendor":"Google","TotalSpend":"450"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Orders",
      "description": "Defines an inline Orders table with Vendor and Spend columns, containing four rows with both canonical and alias vendor names.",
      "output": {"columns":[{"name":"Vendor","type":"any"},{"name":"Spend","type":"any"}],"rows":[{"Vendor":"Microsoft","Spend":"500"},{"Vendor":"MS Corp","Spend":"200"},{"Vendor":"Google","Spend":"300"},{"Vendor":"Alphabet","Spend":"150"}]}
    },
    {
      "name": "Mapping",
      "description": "Defines a TransformationTable with From and To columns that maps known aliases (\"MS Corp\" → \"Microsoft\", \"Alphabet\" → \"Google\") before fuzzy scoring.",
      "output": {"columns":[{"name":"From","type":"any"},{"name":"To","type":"any"}],"rows":[{"From":"MS Corp","To":"Microsoft"},{"From":"Alphabet","To":"Google"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FuzzyGroup applies the TransformationTable mappings first, then groups remaining similar vendors together, producing two canonical groups with summed spend.",
      "output": {"columns":[{"name":"Vendor","type":"any"},{"name":"TotalSpend","type":"number"}],"rows":[{"Vendor":"Microsoft","TotalSpend":"700"},{"Vendor":"Google","TotalSpend":"450"}]}
    }
  ]
}
-->

### Example 3: Lower the threshold to catch more aggressive variations

```powerquery
let
    Cities = #table(
        {"City", "Count"},
        {{"New York", 10}, {"New-York", 5}, {"Newyork", 3}, {"NY City", 2}, {"London", 8}}
    )
in
    Table.FuzzyGroup(
        Cities,
        "City",
        {{"Total", List.Sum, type number}},
        [Threshold = 0.6]
    )
```

<!--output
{"columns":[{"name":"City","type":"any"},{"name":"Total","type":"number"}],"rows":[{"City":"New York","Total":"20"},{"City":"London","Total":"8"}]}
-->
