---
title: "Table.ColumnCount"
slug: "table-columncount"
category: "Table"
description: "Returns the number of columns in the table."
syntax: "Table.ColumnCount(table as table) as number"
returnType: "number"
returnDescription: "The total number of columns in the table."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table whose column count is returned."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-columnnames"
  - "table-rowcount"
  - "table-columnsoftype"
---

## Remarks

`Table.ColumnCount` returns the number of columns in a table as a number. It is equivalent to `List.Count(Table.ColumnNames(table))` but is more direct and expressive of intent. The function is useful for structural validation — for example, asserting that a dataset has the expected number of columns after a transformation, or driving dynamic logic that depends on width rather than named columns.

A common pattern is to combine `Table.ColumnCount` with `Table.ColumnNames` to detect unexpected schema changes: if the count differs from a known baseline, raise an error or add a diagnostic step. This is particularly valuable in automated pipelines where upstream sources may silently add or drop columns.

Note that `Table.ColumnCount` reflects the schema as declared by the table's type, not the number of distinct non-null values in any column.

## Examples

### Example 1: Count columns in the Employees table

```powerquery
let
    Employees = #table(
        type table [EmployeeID = text, FullName = text, Department = text, Title = text, HireDate = date, Salary = number],
        {{"E001","alice smith","Sales","Sales Rep",#date(2021,3,15),55000}}
    )
in
    Table.ColumnCount(Employees)
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"6"}]}
-->

### Example 2: Assert expected column count as a data quality check

```powerquery
let
    Source      = #table({"OrderID","CustomerName","Product","Category","UnitPrice","Quantity","OrderDate","Region"}, {}),
    ExpectedCols = 8,
    ActualCols   = Table.ColumnCount(Source),
    Validated    = if ActualCols = ExpectedCols
                   then Source
                   else error "Unexpected column count: " & Text.From(ActualCols)
in
    ActualCols
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"8"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Source",
      "description": "Creates an empty table with 8 named columns (OrderID through Region) to represent the expected schema.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"Category","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"Quantity","type":"any"},{"name":"OrderDate","type":"any"},{"name":"Region","type":"any"}],"rows":[]}
    },
    {
      "name": "ExpectedCols",
      "description": "Stores the expected column count of 8 as a number for comparison.",
      "output": {"columns":[{"name":"Value","type":"number"}],"rows":[{"Value":"8"}]}
    },
    {
      "name": "ActualCols",
      "description": "Counts the actual number of columns in Source, returning 8.",
      "output": {"columns":[{"name":"Value","type":"number"}],"rows":[{"Value":"8"}]}
    },
    {
      "name": "Validated",
      "description": "Returns Source unchanged if the actual column count matches the expected count of 8, or raises an error describing the mismatch.",
      "output": {"columns":[{"name":"OrderID","type":"any"},{"name":"CustomerName","type":"any"},{"name":"Product","type":"any"},{"name":"Category","type":"any"},{"name":"UnitPrice","type":"any"},{"name":"Quantity","type":"any"},{"name":"OrderDate","type":"any"},{"name":"Region","type":"any"}],"rows":[]}
    },
    {
      "name": "Result",
      "description": "The final output — returns ActualCols, the verified column count of 8.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"8"}]}
    }
  ]
}
-->

### Example 3: Compare column counts before and after a transformation

```powerquery
let
    Source      = #table({"A","B","C","D"}, {{1,2,3,4}}),
    Removed     = Table.RemoveColumns(Source, {"B","D"}),
    Before      = Table.ColumnCount(Source),
    After       = Table.ColumnCount(Removed),
    Dropped     = Before - After
in
    Dropped
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"2"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Source",
      "description": "Creates a one-row table with four columns: A, B, C, and D.",
      "output": {"columns":[{"name":"A","type":"any"},{"name":"B","type":"any"},{"name":"C","type":"any"},{"name":"D","type":"any"}],"rows":[{"A":"1","B":"2","C":"3","D":"4"}]}
    },
    {
      "name": "Removed",
      "description": "Removes columns B and D from Source, leaving only A and C.",
      "output": {"columns":[{"name":"A","type":"any"},{"name":"C","type":"any"}],"rows":[{"A":"1","C":"3"}]}
    },
    {
      "name": "Before",
      "description": "Counts the columns in Source, returning 4.",
      "output": {"columns":[{"name":"Value","type":"number"}],"rows":[{"Value":"4"}]}
    },
    {
      "name": "After",
      "description": "Counts the columns in Removed, returning 2.",
      "output": {"columns":[{"name":"Value","type":"number"}],"rows":[{"Value":"2"}]}
    },
    {
      "name": "Dropped",
      "description": "The final output — subtracts After from Before to compute the number of columns that were removed.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"2"}]}
    }
  ]
}
-->
