---
title: "Table.IsEmpty"
slug: "table-isempty"
category: "Table"
description: "Returns true if a table contains no rows."
syntax: "Table.IsEmpty(table as table) as logical"
returnType: "logical"
returnDescription: "true if the table has zero rows, false otherwise."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to check."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-rowcount"
  - "table-selectrows"
---

## Remarks

`Table.IsEmpty` returns `true` if the table has no rows. This is more readable and efficient than checking `Table.RowCount(table) = 0`. It is commonly used in conditional logic — for example, checking whether a filter returned any results before performing further operations.

## Examples

### Example 1: Check if filtered table is empty

Filter Sales for a non-existent region and check whether the result is empty.

Input: `Sales`

```powerquery
let
    Filtered = Table.SelectRows(Sales, each [Region] = "South"),
    IsEmpty = Table.IsEmpty(Filtered)
in
    #table({"IsEmpty"}, {{IsEmpty}})
```

<!--output
{"columns":[{"name":"IsEmpty","type":"logical"}],"rows":[{"IsEmpty":true}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Filtered",
      "description": "Filters the Sales table to rows where Region equals \"South\", which matches no rows in the sample data, producing an empty table.",
      "output": {"columns":[{"name":"OrderID","type":"number"},{"name":"CustomerName","type":"text"},{"name":"Product","type":"text"},{"name":"Category","type":"text"},{"name":"UnitPrice","type":"number"},{"name":"Quantity","type":"number"},{"name":"OrderDate","type":"date"},{"name":"Region","type":"text"}],"rows":[]}
    },
    {
      "name": "IsEmpty",
      "description": "Calls Table.IsEmpty on the filtered table, returning true because the table contains zero rows.",
      "output": {"columns":[{"name":"Value","type":"logical"}],"rows":[{"Value":true}]}
    },
    {
      "name": "Result",
      "description": "The final output — wraps the IsEmpty logical value in a single-row table for display, showing true to confirm no South-region orders exist.",
      "output": {"columns":[{"name":"IsEmpty","type":"logical"}],"rows":[{"IsEmpty":true}]}
    }
  ]
}
-->

### Example 2: Check a non-empty table

Check whether the full Sales table is empty.

Input: `Sales`

```powerquery
let
    IsEmpty = Table.IsEmpty(Sales)
in
    #table({"IsEmpty"}, {{IsEmpty}})
```

<!--output
{"columns":[{"name":"IsEmpty","type":"logical"}],"rows":[{"IsEmpty":false}]}
-->
