---
title: "Table.FirstValue"
slug: "table-firstvalue"
category: "Table"
description: "Returns the value in the first row and first column of the table, or a default value if the table is empty."
syntax: "Table.FirstValue(table as table, optional default as nullable any) as any"
returnType: "any"
returnDescription: "The scalar value from the first cell of the table, or the default if the table is empty."
parameters:
  - name: "table"
    type: "table"
    required: true
    description: "The table to read the first value from."
  - name: "default"
    type: "any"
    required: false
    description: "Optional value to return if the table is empty. Defaults to null."
compatibility:
  pbiDesktop: true
  pbiService: true
  excelDesktop: true
  excelOnline: true
  dataflows: true
  fabricNotebooks: true
relatedFunctions:
  - "table-first"
  - "table-singlerow"
  - "table-selectrows"
---

## Remarks

`Table.FirstValue` extracts a single scalar value from the first row and first column of a table. It is a convenience shorthand for `Table.First(table)[firstColumnName]` and is most commonly used to read a single expected result after filtering — such as a configuration parameter from a settings table, a count from a summarized dataset, or a lookup result from a reference table.

When the table is empty, `Table.FirstValue` returns `null` by default, or the specified `default` value if provided. This makes it safer than `Table.First(table)[Column]` in scenarios where the filter might yield no rows, because chaining field access on `null` would raise an error.

The function always reads the value from the first column. If you need a value from a specific column that is not first, use `Table.First(table)[ColumnName]` instead. Alternatively, project the table to only the target column with `Table.SelectColumns` before calling `Table.FirstValue`.

## Examples

### Example 1: Read a configuration value from a parameters table

```powerquery
let
    Parameters = #table(
        {"Name", "Value"},
        {{"StartDate", "2024-01-01"}, {"EndDate", "2024-12-31"}, {"MaxRows", "1000"}}
    ),
    Filtered   = Table.SelectRows(Parameters, each [Name] = "MaxRows"),
    Projected  = Table.SelectColumns(Filtered, {"Value"})
in
    Table.FirstValue(Projected)
```

<!--output
{"columns":[{"name":"Result","type":"any"}],"rows":[{"Result":"1000"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Parameters",
      "description": "Defines an inline parameters table with Name and Value columns containing three configuration entries.",
      "output": {"columns":[{"name":"Name","type":"text"},{"name":"Value","type":"text"}],"rows":[{"Name":"StartDate","Value":"2024-01-01"},{"Name":"EndDate","Value":"2024-12-31"},{"Name":"MaxRows","Value":"1000"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters the Parameters table to the single row where Name equals \"MaxRows\".",
      "output": {"columns":[{"name":"Name","type":"text"},{"name":"Value","type":"text"}],"rows":[{"Name":"MaxRows","Value":"1000"}]}
    },
    {
      "name": "Projected",
      "description": "Selects only the Value column from the filtered row, leaving a single-column, single-row table.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[{"Value":"1000"}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FirstValue reads the scalar from the first cell of the projected table, returning the string \"1000\".",
      "output": {"columns":[{"name":"Result","type":"any"}],"rows":[{"Result":"1000"}]}
    }
  ]
}
-->

### Example 2: Return a default when no match is found

```powerquery
let
    Parameters = #table(
        {"Name", "Value"},
        {{"StartDate", "2024-01-01"}}
    ),
    Filtered  = Table.SelectRows(Parameters, each [Name] = "Threshold"),
    Projected = Table.SelectColumns(Filtered, {"Value"})
in
    Table.FirstValue(Projected, "100")
```

<!--output
{"columns":[{"name":"Result","type":"any"}],"rows":[{"Result":"100"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Parameters",
      "description": "Defines an inline parameters table with a single entry: StartDate = \"2024-01-01\".",
      "output": {"columns":[{"name":"Name","type":"text"},{"name":"Value","type":"text"}],"rows":[{"Name":"StartDate","Value":"2024-01-01"}]}
    },
    {
      "name": "Filtered",
      "description": "Filters the Parameters table to rows where Name equals \"Threshold\", which matches nothing and returns an empty table.",
      "output": {"columns":[{"name":"Name","type":"text"},{"name":"Value","type":"text"}],"rows":[]}
    },
    {
      "name": "Projected",
      "description": "Selects only the Value column from the empty filtered table, producing an empty single-column table.",
      "output": {"columns":[{"name":"Value","type":"text"}],"rows":[]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FirstValue on the empty table returns the supplied default value \"100\" instead of null.",
      "output": {"columns":[{"name":"Result","type":"any"}],"rows":[{"Result":"100"}]}
    }
  ]
}
-->

### Example 3: Extract the lowest unit price from the Products table

```powerquery
let
    Products = #table(
        type table [ProductID = number, ProductName = text, Price = number, InStock = logical],
        {{1,"Widget A",25.00,true},{2,"Gadget B",50.00,true},{3,"Widget C",15.00,false}}
    ),
    Sorted   = Table.Sort(Products, {{"Price", Order.Ascending}}),
    PriceCol = Table.SelectColumns(Sorted, {"Price"})
in
    Table.FirstValue(PriceCol)
```

<!--output
{"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"15"}]}
-->
<!--steps
{
  "steps": [
    {
      "name": "Products",
      "description": "Defines an inline Products table with typed columns for ProductID, ProductName, Price, and InStock containing three product rows.",
      "output": {"columns":[{"name":"ProductID","type":"number"},{"name":"ProductName","type":"text"},{"name":"Price","type":"number"},{"name":"InStock","type":"logical"}],"rows":[{"ProductID":1,"ProductName":"Widget A","Price":25,"InStock":true},{"ProductID":2,"ProductName":"Gadget B","Price":50,"InStock":true},{"ProductID":3,"ProductName":"Widget C","Price":15,"InStock":false}]}
    },
    {
      "name": "Sorted",
      "description": "Sorts the Products table by Price ascending so the cheapest product appears in the first row.",
      "output": {"columns":[{"name":"ProductID","type":"number"},{"name":"ProductName","type":"text"},{"name":"Price","type":"number"},{"name":"InStock","type":"logical"}],"rows":[{"ProductID":3,"ProductName":"Widget C","Price":15,"InStock":false},{"ProductID":1,"ProductName":"Widget A","Price":25,"InStock":true},{"ProductID":2,"ProductName":"Gadget B","Price":50,"InStock":true}]}
    },
    {
      "name": "PriceCol",
      "description": "Selects only the Price column from the sorted table, isolating the values so Table.FirstValue reads the correct column.",
      "output": {"columns":[{"name":"Price","type":"number"}],"rows":[{"Price":15},{"Price":25},{"Price":50}]}
    },
    {
      "name": "Result",
      "description": "The final output — Table.FirstValue returns the scalar from the first cell of PriceCol, which is the lowest price 15.",
      "output": {"columns":[{"name":"Result","type":"number"}],"rows":[{"Result":"15"}]}
    }
  ]
}
-->
